### PR TITLE
[15.0][MIG] announcement: Migration to 15.0

### PR DESCRIPTION
**Pull request by chienandalu**
- Mainly adapt to ES6 (we'll have to wait for owl on 16.0)

cc @Tecnativa TT40347

ping @CarlosRoca13

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Tested on runboat. Seems to work OK. Only that CI is red.

**Review by CarlosRoca13 — APPROVED** [review]
:+1:

**Comment by chienandalu** [comment]
There is some stuff to do yet (pre-commit mainly)

**Pull request merged**
