### PR TITLE
12.0 mig sequence reset period

### PR DESCRIPTION
**Pull request by jaumeplanas**

### CODE REVIEW

**Comment by etobella** [comment]
There exists a Pr for this module: #64 
It was already done by you. You should close one of the PRs.

**Comment by jaumeplanas** [comment]
@etobella #71 is for module sequence_check_digit. This one is for module sequence_reset_period, it should replace old #64 one because of its messed commit history including unwanted merges.

**Comment by etobella** [comment]
I made a mistake with the PR number, I edited my comment. Sorry :wink:

**Comment by JayVora-SerpentCS** [comment]
LGTM !

**Review by etobella — APPROVED** [review]
@jarroyomorales

**Review by jarroyomorales — APPROVED** [review]
LGTM :+1:

**Pull request merged**
