### PR TITLE
[17.0][MIG] base_substate: Migration to 17.0

### PR DESCRIPTION
**Pull request by MohamedOsman7**
Follow-up: #855 (also #885)
Same changes but with a clean commit history

### CODE REVIEW

**Review by CRogos — APPROVED** [review]
LGTM

**Comment by MohamedOsman7** [comment]
@StefanRijnhart @rousseldenis @bosd Could you please make a review?

**Review by miguel-S73 — APPROVED** [review]

**Comment by CRogos** [comment]
@pedrobaeza could you please merge and close the other PRs?

**Pull request merged**
