### PR TITLE
[14.0][ADD] sequence_range_end

### PR DESCRIPTION
**Pull request by kittiu**
When configure for sequence prefix/suffix, this module add option `range_end_` in addition to `range_`.
to use the ending of the range instead of the current date, e.g. %(range_end_year)s instead of %(year)s.

TODO:

- [x] Test

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
~~If I understand correctly, my PR https://github.com/OCA/server-ux/pull/347 is a more generic implementation of this. It is ported to 14.0 in https://github.com/OCA/server-ux/pull/349.~~

Narrator: "he did not understand correctly"

**Comment by kittiu** [comment]
cc @ps-tubtim @newtratip

**Review by newtratip — APPROVED** [review]

**Review by Saran440 — APPROVED** [review]
LGTM :+1:

**Review by ps-tubtim — APPROVED** [review]

**Comment by ps-tubtim** [comment]
@kittiu I fix about the case prefix that has "range_end_" and normal eg. %(month)s . Could you review it?

Sequence Setting
Selection_069

Before
Peek 2021-11-16 15-37

After
Peek 2021-11-16 15-43

**Pull request merged**
