### PR TITLE
[14.0][MIG] base_substate

### PR DESCRIPTION
**Pull request by kittiu**
Moved from https://github.com/OCA/server-ux/pull/268

### CODE REVIEW

**Review by hkapatel-initos — CHANGES_REQUESTED** [review]
Hello, @kittiu Can you please squash all the commits in this [MIG] base_substate: Migration to 14.0

**Comment by kittiu** [comment]
> Hello, @kittiu Can you please squash all the commits in this [MIG] base_substate: Migration to 14.0

rebased and squashed, thanks!

**Review by dsolanki-initos — APPROVED** [review]
Code review and functional test LGTM

**Comment by dsolanki-initos** [comment]
it would be nice we get the reviews here.

**Comment by dsolanki-initos** [comment]
it would be nice we get the reviews here.

**Comment by dsolanki-initos** [comment]
it would be nice we get the reviews here.

**Comment by dsolanki-initos** [comment]
it would be nice we get the reviews here.

**Comment by dsolanki-initos** [comment]
@chafique-delli and @simahawk  It would be nice if you add reviews here.

**Comment by dsolanki-initos** [comment]
@chafique-delli and @simahawk It would be nice if you add reviews here.

**Comment by dsolanki-initos** [comment]
@newtratip and @HaraldPanten it would be nice if you add reviews here.

**Comment by HaraldPanten** [comment]
Hi @dsolanki-initos it seems to be OK for me but, to be honest, this module excedes my technical skills 😔. I can't tell you if it's 100% correct.

**Review by newtratip — APPROVED** [review]
LGTM :+1:

**Comment by dsolanki-initos** [comment]
@dreispt Can we merge this ?

**Pull request merged**
