### PR TITLE
[17.0][MIG] base_export_manager: Migration to 17.0

### PR DESCRIPTION
**Pull request by david-s73**

### CODE REVIEW

**Comment by benjilluch** [comment]
Hello, this PR has been stuck for a while. Is there anything I can do to help unblock it? From what I see, the test coverage doesn't meet the expected threshold. Is it really necessary?

**Comment by chienandalu** [comment]
Coverage isn't blocking. It simply has no reviewers

**Comment by benjilluch** [comment]
I’m sorry to hear that there aren’t any reviewers assigned. If I can help, I’d be happy to assist!

**Comment by chienandalu** [comment]
There's no need to assign reviewers, anyone can do it any time. You can ask the contributor for a re-push that triggers the runboat again to be able to test the funcionallity and you can do a full review in the context of the new version.

**Comment by benjilluch** [comment]
@david-s73 Could you please do a re-push to trigger the runboat again? That way I can test the functionality and perform a full review on the latest version. Thanks!

**Comment by david-s73** [comment]
@benjilluch Done

**Comment by benjilluch** [comment]
I’ve just tested it on Runboat, and it works well.

**Comment by benjilluch** [comment]
@chienandalu Could I ask if anything else is needed on this?

**Comment by benjilluch** [comment]
@pedrobaeza Can you look into speeding up this issue?

**Comment by pedrobaeza** [comment]
You need to enroll reviewers

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review

One way is that you review other PRs, and ask in exchange that they review yours.

**Review by ced-adhoc — APPROVED** [review]

**Comment by ced-adhoc** [comment]
LGTM

**Review by mav-adhoc — APPROVED** [review]

**Review by jcadhoc — APPROVED** [review]

**Comment by ced-adhoc** [comment]
Hi @pedrobaeza , could you please check this pr? thanks!

**Pull request merged**
