### PR TITLE
[MIG] base_rule_visibility_restriction: Migration to 16.0

### PR DESCRIPTION
**Pull request by SirAionTech**
Standard migration from `14.0` (https://github.com/OCA/server-ux/tree/10d1201c013eb86fc8cf6c3e03fd9676ddbffaf3/base_rule_visibility_restriction).

Added a test for better coverage.

### CODE REVIEW

**Review by kikopeiro — APPROVED** [review]
:+1: LGTM ( without code review)

**Comment by SirAionTech** [comment]
@GuillemCForgeFlow maybe you'd like to have a look?
I just noticed you are the maintainer of the module, but for some reason @OCA-git-bot did not mention you.

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! code and functional review 👍🏿 
thank you for adding the test case, helps a lot 😄

**Comment by SirAionTech** [comment]
> LGTM! code and functional review 👍🏿
thank you for adding the test case, helps a lot 😄

Would you like to merge maybe? See how in https://github.com/OCA/oca-github-bot?tab=readme-ov-file#commands.

**Pull request merged**
