### PR TITLE
[16.0][MIG] sequence_reset_period: Migration to 16.0.

### PR DESCRIPTION
**Pull request by oihane**

### CODE REVIEW

**Review by anajuaristi — APPROVED** [review]

**Comment by anajuaristi** [comment]
Functionally tested LGTM 👍

**Review by Mantux11 — APPROVED** [review]
Tested Functionally in module, that depends on this, LGTM.

**Review by gaikaz — APPROVED** [review]

**Comment by gaikaz** [comment]
@OCA/tools-maintainers 
Sorry to keep pinging you guys like that, but this is an easy merge. 🙏🏻 Thank you.

**Pull request merged**
