### PR TITLE
[13.0][base_tier_validation][fix] Allow to search for validated=False and rejected = False

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
cc @AdriaGForgeFlow @AaronHForgeFlow @LoisRForgeFlow @kittiu

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Code review :+1:

**Review by kittiu — APPROVED** [review]
LGTM

**Review by etobella — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
Thanks for your reviews!

**Review by AdriaGForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
To be forward ported.

**Pull request merged**
