### PR TITLE
[13.0][IMP] base_tier_validation*: Backport of commits from version 14.0 to 13.0 

### PR DESCRIPTION
**Pull request by albariera**
In this PR I have taken the commits done after migration to 14.0 that were not present at 13.0

### CODE REVIEW

**Review by etobella — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
Tested, everything seems good.

Thanks :+1:

**Comment by LoisRForgeFlow** [comment]
Fixing travis issue here: https://github.com/OCA/server-ux/pull/408.

**Pull request merged**
