### PR TITLE
[14.0][FWD] base_tier_validation: Forward updates from 13.0

### PR DESCRIPTION
**Pull request by dzungtran89**
Porting PRs:
- #296 
- #343 
- #356

### CODE REVIEW

**Review by sebalix — APPROVED** [review]

**Comment by sebalix** [comment]
@ForgeFlow are you OK with these ports?

**Review by kittiu — APPROVED** [review]
LGTM

**Comment by kittiu** [comment]
Hello, I have some question,

The old bahavior, when the doc status is set to "Cancelled", the review table is still there. Only when set to draft or restart the validation then it is removed.

This PR #343 will remove table when doc status is cancelled.

IMHO, I would prefer to see Review table on cancelled document, why not? @sergio-teruel

**Comment by simahawk** [comment]
@kittiu @LoisRForgeFlow @dzungtran89 any feedback on https://github.com/OCA/server-ux/pull/412#issuecomment-1000144278 ?

Otherwise, can we merge?

**Comment by dzungtran89** [comment]
Hi @simahawk , I don't have any feedback, I just thought that PR is worth to port

**Comment by sergio-teruel** [comment]
@kittiu , have you tried to request the validation of an order and later cancel it?
This is the issue, you can not cancel a sale order under a request validation... 
I think that the PR https://github.com/OCA/server-ux/pull/343 must be keep...

**Comment by simahawk** [comment]
can we merge then?

**Comment by kittiu** [comment]
> can we merge then?

I am ok to merge too.

**Pull request merged**
