### PR TITLE
[12.0][MIG] barcode_action

### PR DESCRIPTION
**Pull request by jarroyomorales**
Migration to 12.0 of barcode_action. No changes.

@etobella

### CODE REVIEW

**Review by etobella — APPROVED** [review]
No real changes. It could be fast-tracked.

LGTM :+1:

**Review by tbaden — APPROVED** [review]
thanks for the work 👍 
I did a code review: LGTM

Not mandatory, but you could fix these travis warnings:
<details><summary>logs</summary>

************* Module barcode_action
barcode_action/static/src/js/action_barcode_form.js:2: [W7903(javascript-lint), ] Expected indentation of 4 spaces but found 0. [Error/indent]
barcode_action/static/src/js/action_barcode_form.js:4: [W7903(javascript-lint), ] Expected indentation of 4 spaces but found 0. [Error/indent]
barcode_action/static/src/js/action_barcode_form.js:6: [W7903(javascript-lint), ] Expected indentation of 4 spaces but found 0. [Error/indent]
barcode_action/static/src/js/action_barcode_form.js:7: [W7903(javascript-lint), ] Expected indentation of 8 spaces but found 4. [Error/indent]
barcode_action/static/src/js/action_barcode_form.js:7: [W7903(javascript-lint), ] 'activeBarcode' is defined but never used. [Error/no-unused-vars]
barcode_action/static/src/js/action_barcode_form.js:8: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
barcode_action/static/src/js/action_barcode_form.js:9: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
barcode_action/static/src/js/action_barcode_form.js:10: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
barcode_action/static/src/js/action_barcode_form.js:11: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 20. [Error/indent]
barcode_action/static/src/js/action_barcode_form.js:12: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 20. [Error/indent]
barcode_action/static/src/js/action_barcode_form.js:13: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 20. [Error/indent]
barcode_action/static/src/js/action_barcode_form.js:14: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 16. [Error/indent]
barcode_action/static/src/js/action_barcode_form.js:15: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 20. [Error/indent]
barcode_action/static/src/js/action_barcode_form.js:15: [W7903(javascript-lint), ] Missing space before opening brace. [Error/space-before-blocks]
barcode_action/static/src/js/action_barcode_form.js:16: [W7903(javascript-lint), ] Expected indentation of 20 spaces but found 24. [Error/indent]
barcode_action/static/src/js/action_barcode_form.js:17: [W7903(javascript-lint), ] Expected indentation of 20 spaces but found 24. [Error/indent]
barcode_action/static/src/js/action_barcode_form.js:18: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 20. [Error/indent]
barcode_action/static/src/js/action_barcode_form.js:19: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 16. [Error/indent]
barcode_action/static/src/js/action_barcode_form.js:20: [W7903(javascript-lint), ] Expected indentation of 8 spaces but found 4. [Error/indent]
barcode_action/static/src/js/action_barcode_form.js:21: [W7903(javascript-lint), ] Expected indentation of 4 spaces but found 0. [Error/indent]
barcode_action/static/src/js/action_barcode_widget.js:2: [W7903(javascript-lint), ] Expected indentation of 4 spaces but found 0. [Error/indent]
barcode_action/static/src/js/action_barcode_widget.js:4: [W7903(javascript-lint), ] Expected indentation of 4 spaces but found 0. [Error/indent]
barcode_action/static/src/js/action_barcode_widget.js:5: [W7903(javascript-lint), ] Expected indentation of 4 spaces but found 0. [Error/indent]
barcode_action/static/src/js/action_barcode_widget.js:7: [W7903(javascript-lint), ] Expected indentation of 4 spaces but found 0. [Error/indent]
barcode_action/static/src/js/action_barcode_widget.js:8: [W7903(javascript-lint), ] Expected indentation of 8 spaces but found 4. [Error/indent]
barcode_action/static/src/js/action_barcode_widget.js:8: [W7903(javascript-lint), ] Missing space before function parentheses. [Error/space-before-function-paren]
barcode_action/static/src/js/action_barcode_widget.js:9: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
barcode_action/static/src/js/action_barcode_widget.js:10: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
barcode_action/static/src/js/action_barcode_widget.js:11: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
barcode_action/static/src/js/action_barcode_widget.js:12: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
barcode_action/static/src/js/action_barcode_widget.js:13: [W7903(javascript-lint), ] Expected indentation of 20 spaces but found 16. [Error/indent]
barcode_action/static/src/js/action_barcode_widget.js:14: [W7903(javascript-lint), ] Expected indentation of 16 spaces but found 12. [Error/indent]
barcode_action/static/src/js/action_barcode_widget.js:14: [W7903(javascript-lint), ] Missing trailing comma. [Error/comma-dangle]
barcode_action/static/src/js/action_barcode_widget.js:15: [W7903(javascript-lint), ] Expected indentation of 12 spaces but found 8. [Error/indent]
barcode_action/static/src/js/action_barcode_widget.js:16: [W7903(javascript-lint), ] Expected indentation of 8 spaces but found 4. [Error/indent]
barcode_action/static/src/js/action_barcode_widget.js:17: [W7903(javascript-lint), ] Expected indentation of 4 spaces but found 0. [Error/indent]
barcode_action/static/src/js/action_barcode_widget.js:18: [W7903(javascript-lint), ] Expected indentation of 4 spaces but found 0. [Error/indent]
barcode_action/static/src/js/action_barcode_widget.js:20: [W7903(javascript-lint), ] Expected indentation of 4 spaces but found 0. [Error/indent]
barcode_action/static/src/js/action_barcode_widget.js:21: [W7903(javascript-lint), ] Expected indentation of 8 spaces but found 4. [Error/indent]
barcode_action/static/src/js/action_barcode_widget.js:22: [W7903(javascript-lint), ] Expected indentation of 4 spaces but found 0. [Error/indent]

</details>

**Comment by jarroyomorales** [comment]
@tbaden Done!

**Comment by shepilov-vladislav** [comment]
Can be this PR will be merged?

**Pull request closed without merging**
