### PR TITLE
[IMP] add security groups to mass editing action

### PR DESCRIPTION
**Pull request by ovnicraft**

### CODE REVIEW

**Comment by ovnicraft** [comment]
@pedrobaeza its here

**Review by pedrobaeza — APPROVED** [review]
Please squash commits together

**Comment by ovnicraft** [comment]
@pedrobaeza done, wait for greens

**Comment by ovnicraft** [comment]
@moylop260 its ready to merge

**Comment by pedrobaeza** [comment]
@sbidoul see this thread: there seems to be something incorrect in the ocabot.

**Comment by sbidoul** [comment]
@pedrobaeza I see here that @moylop260 submitted an invalid merge command 6 hours ago, which was ignored (there is currently no error report in that case, that's normal). The error message to @ovnicraft is strange. Could it be that you submitted a merge command then deleted it @ovnicraft ?

**Comment by ovnicraft** [comment]
@sbidoul yes i tried `/ocabot merge`  and then delete it.

**Comment by pedrobaeza** [comment]
Mistery solved!

**Pull request merged**
