### PR TITLE
[15.0][MIG] base_custom_filter: Migration to 15.0

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
This migration is done by cherry-pick of each commit from commit history because there are issues using [maintainer-tools](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch) for migration.
I squash the two commit [[MIG] base_custom_filter: Migration to 14.0 ](https://github.com/OCA/server-ux/commit/7fda605b7ca33a3042d662e537460b639f38ea86) and [[IMP] base_custom_filter: black, isort, prettier ](https://github.com/OCA/server-ux/commit/f996c8dfdd376591393e404191de2bf902a2aa35) into [[MIG] base_custom_filter: Migration to 14.0](https://github.com/OCA/server-ux/pull/573/commits/e8f6dcf4ccc4511bb9d2225c3388413144264a2b) because these two commits have the same changes and I got nothing to commit when commit [MIG] base_custom_filter: Migration to 14.0 after commit [IMP] base_custom_filter: black, isort, prettier.

nothingtocommit

Related issue: https://github.com/OCA/server-ux/issues/571
@qrtl

### CODE REVIEW

**Review by yostashiro — APPROVED** [review]
Functional review. 👍

**Review by vincent-cowboy — APPROVED** [review]
LGTM (functional review). Thank you for this PR 🙏

**Comment by victoralmau** [comment]
Please, cherry-pick https://github.com/OCA/server-ux/pull/657 to commit history

**Review by victoralmau — APPROVED** [review]
Code and functional review OK

**Pull request merged**
