### PR TITLE
[14.0][FIX] base_tier_validation: condition state

### PR DESCRIPTION
**Pull request by Saran440**
check condition `vals.get(self._state_field)` is not null for other module use write function it will error (i.e. base_exception)

- [ ] Test script

### CODE REVIEW

**Comment by kittiu** [comment]
@rousseldenis can you check this?
This should be a safe fix, and make it work with base_exception.

**Comment by kittiu** [comment]
@Saran440 please check Travis.

**Comment by rousseldenis** [comment]
@Saran440 @kittiu IMHO, the complete content of the condition should be included in a function in order to have a better inehritance possibilities and comprehension

**Comment by rousseldenis** [comment]
With a good comment

**Comment by Saran440** [comment]
okay, it move on my project.
Thank you :)

**Pull request closed without merging**
