### PR TITLE
[Update] mass_editing icon

### PR DESCRIPTION
**Pull request by jonisunz**

### CODE REVIEW

**Review by pedrobaeza — COMMENTED** [review]
Thanks for creating an specific icon. Several things:

- Can you round the corners in the same style as v12 icons?
- Can you provide the source in SVG for further modifications?

**Comment by pedrobaeza** [comment]
Please squash commits into one.

**Review by HaraldPanten — APPROVED** [review]
Just attend squash comments, but icon LGTM

**Comment by simahawk** [comment]
@pedrobaeza seems good. Fine for you?

**Comment by pedrobaeza** [comment]
Yes, it's just that the contributor didn't drop a comment and I wasn't aware that the requested changes were done. Thanks for the cool icon!

/ocabot merge patch

**Comment by pedrobaeza** [comment]
Can you do the same for 13.0?

**Pull request merged**
