### PR TITLE
[14.0][ENH] base_tier_validation_report, see all reviews group

### PR DESCRIPTION
**Pull request by kittiu**
This PR add new groups, See All Tier Reviews, to allow any users even with no right to see the target model, at least see the report.

image

### CODE REVIEW

**Comment by kittiu** [comment]
cc @ps-tubtim

**Review by ps-tubtim — APPROVED** [review]

**Comment by kittiu** [comment]
Also, I review view a little bit for usability.

**Comment by francesco-ooops** [comment]
@kittiu can you rebase for functional testing?

**Comment by kittiu** [comment]
May I test using the command.

**Comment by kittiu** [comment]
Rebased

**Comment by francesco-ooops** [comment]
Hi @kittiu , a couple questions: 

1) what is the flow of this module? should I set any access right to a user? or any user is allowed to see all reports?

2) where does the "dashboards" app come from? I'm not very familiar with this module. 

It would be good if you could expand in this PR the description/usage files for https://github.com/OCA/server-ux/tree/14.0/base_tier_validation_report :)

Thanks!

**Comment by francesco-ooops** [comment]
@kittiu gentle reminder :)

**Comment by kittiu** [comment]
Hi @francesco-ooops 
1. This is just the report showing tier.review this way. It is more a report than operation. It allow user to see not only pending but the past reviews he/she did.
2. Dashboard is base module, no need to install anything. Normally, if you on any screen, you can save your current view into Dashboard. (I just use the Dashboard menu to host this report too).

You don't need to setup security, everyone will see their own reviews. Except for user who want to see all other people reviews too then he/can can has View All Reviews.

I think it is pretty simple and self explanatory. :)

**Comment by francesco-ooops** [comment]
Hi @kittiu , sorry but I would really appreciate if you could take some time to explain step by step how to use this module :)

> It allow user to see not only pending but the past reviews he/she did.

Where/how can the user see this?

**Review by francesco-ooops — APPROVED** [review]
@kittiu ok, I understood the flow, was just unclear to me how the menu is automatically added to dashboards - this is something I would add to module description, as it's not very user friendly as it is

functional review ok!

**Comment by francesco-ooops** [comment]
@kittiu I think just changing description like this is enough: 

> This module provide additional reports related to Tier Validation
> 
> My Reviews (pending, approved, rejected)
> All Reviews (pending, approved, rejected)
> 
> These reports are accessible in Dashboard app

then if you can squash commits I think we're good for merge :)

**Comment by Saran440** [comment]
@francesco-ooops Thank you for your review, I fixed it.

**Comment by francesco-ooops** [comment]
@OCA/tools-maintainers good for merge?

**Comment by thomaspaulb** [comment]
@francesco-ooops I don't know if it will work because Codecov is at -0.10%, but lets see

**Pull request merged**
