### PR TITLE
[11.0][ADD] easy_switch_user

### PR DESCRIPTION
**Pull request by tarteo**
This module lets administrators and developers quickly change user to test e.g. access rights.

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Probably not due to this module, but I can't access runbot right now.

**Review by StefanRijnhart — COMMENTED** [review]
I like this module! The code looks clean as well. What I don't like is that the entered passwords are stored unencrypted in the session storage on the server, including the password of the original user when they switch back. Can you make it so that the cookie only contains the list of authenticated users and bypass the password check when switching users?

**Comment by tarteo** [comment]
@StefanRijnhart The passwords are not stored server side. I use html5 session storage which is stored client side. This storage is cleared when you close the browser. https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

**Comment by StefanRijnhart** [comment]
Indeed, I misunderstood the concept of session storage, and the cleartext password of the current user is put in the server side session by Odoo itself. Thanks for clarifying! I guess this is basically alright for security, but maybe this mechanism can be made explicit and/or optional? I'm thinking of a checkbox

    [x] Store this password in your browser until you close this tab

So that you cannot trick other users to enter their password to switch to their account temporarily and harvest their passwords.

Another thing: can you clear this data from the session storage upon logout?

**Comment by tarteo** [comment]
@StefanRijnhart Yes sounds good! I'll add it. Thanks for your feedback. :)

**Comment by tarteo** [comment]
@StefanRijnhart Hey, I've added the checkbox and clearing the session storage opun logout. Can you re-review ;) when you have time?

**Review by StefanRijnhart — APPROVED** [review]
Thank you for the quick followup and the nice module!

**Review by LoisRForgeFlow — APPROVED** [review]
Tested locally, great one, thanks! :+1:

**Review by astirpe — APPROVED** [review]
Code review: OK

**Pull request merged**
