### PR TITLE
[12.0][MIG] mass_editing: Migration to 12.0

### PR DESCRIPTION
**Pull request by hugho-ad**

### CODE REVIEW

**Comment by hugho-ad** [comment]
@simahawk 

Your comments at https://github.com/OCA/server-ux/pull/29 were applied here

**Comment by hugho-ad** [comment]
@moylop260 

could you help me by reviewing this, please?

**Comment by moylop260** [comment]
Could you upload a video working in runbot, please?
-- 
Moisés López Calderón
Mobile: (+521) 477-752-22-30
Twitter: @moylop260
hangout: moylop260@vauxoo.com
http://www.vauxoo.com - Odoo Gold Partner
Twitter: @vauxoo

**Comment by hugho-ad** [comment]
Here is the video https://youtu.be/T96KEUovfcQ

Regards!

**Pull request merged**
