### PR TITLE
[13.0][IMP] base_tier_validation: support to search for records where validation has not yet started

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Othewise this filter is not working in https://github.com/OCA/account-invoicing/tree/13.0/account_move_tier_validation

image

### CODE REVIEW

**Review by JordiMForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
run pre-commit

**Review by AaronHForgeFlow — APPROVED** [review]

**Review by AdriaGForgeFlow — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
A test case would be welcomed

**Comment by JordiBForgeFlow** [comment]
@LoisRForgeFlow added tests

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

**Pull request merged**
