### PR TITLE
[14.0][ADD] base_disable_field_translate

### PR DESCRIPTION
**Pull request by kittiu**
When it is sure user don't want to use data translation. Translation of data can cause problem than being useful.
This technical module simply remove translation from all fields' data (same as set translate=False)

Selection_555

After install and restart server

image

### CODE REVIEW

**Comment by kittiu** [comment]
Looks like this disable of translation will affect tests in other module, i.e.,

```
FAIL: TestMassEditing.test_mass_edit_partner_title
Traceback (most recent call last):
  File "/home/travis/build/OCA/server-ux/setup/mass_editing/odoo/addons/mass_editing/tests/test_mass_editing.py", line 110, in test_mass_edit_partner_title
    "Translation for Partner Title's Abbreviation " "was not loaded properly.",
AssertionError: 0 != 1 : Translation for Partner Title's Abbreviation was not loaded properly.
```

Anyone know how solve this? Anyway to ensure this module is installed last?

**Comment by newtratip** [comment]
This module is disable translate `menu item`, `field label`, ... too (No only field's data). I think these should be translated if install multiple language in the system.

**Comment by kittiu** [comment]
When this module is installed, or uninstalled. The server need restart to take effect (this is in README). 

I still not find the problem, i.e., th_TH

Selection_591

With this module installed + restart

Selection_590

Can you give me exact steps to get the problem?

**Comment by kittiu** [comment]
OK, I think I know how you get to the problem. Please make sure this module is uninstalled when generate missing terms. I added in the README as following,

* Restart server after install or uninstall for this module to take effect
* Make sure this module is not installed, if you want to use Translations > Generate Missing Terms, as translated terms won't be loaded

**Comment by kittiu** [comment]
@newtratip this should work now. Can you try again?

**Comment by kittiu** [comment]
@newtratip have you test yet?

**Pull request closed without merging**
