### PR TITLE
[14.0][IMP] base_tier_validation_server_action: Avoid recursive server actions

### PR DESCRIPTION
**Pull request by rousseldenis**
@kittiu

### CODE REVIEW

**Comment by kittiu** [comment]
@rousseldenis what is the case when this happen? And where are you are passing context "server_action_tier" from?

**Comment by rousseldenis** [comment]
The exact one is a user in validation group that changes a field manually that triggers a server action that changes that field.

**Comment by kittiu** [comment]
> changes a field manually

IC, thanks for the fix.

**Review by kittiu — APPROVED** [review]

**Review by Saran440 — APPROVED** [review]

**Pull request merged**
