### PR TITLE
[13.0][FIX] base_optional_quick_create: add mail dependency

### PR DESCRIPTION
**Pull request by maisim**
Fix

psycopg2.ProgrammingError: column ir_model.is_mail_activity does not exist
LINE 1: ...","ir_model"."is_mail_thread" as "is_mail_thread","ir_model"...

on upgrade from 12.0 to 13.0

### CODE REVIEW

**Comment by maisim** [comment]
:hand:  @OCA/tools-maintainers

**Comment by thomaspaulb** [comment]
Would like to fasttrack but not finding a reference to `is_mail_activity` in the [module code](https://github.com/OCA/server-ux/blob/13.0/base_optional_quick_create) ?

**Comment by maisim** [comment]
> Would like to fasttrack but not finding a reference to `is_mail_activity` in the [module code](https://github.com/OCA/server-ux/blob/13.0/base_optional_quick_create) ?

It is just to get the mail module updated before this one to avoid :

psycopg2.ProgrammingError: column ir_model.is_mail_activity does not exist
LINE 1: ...","ir_model"."is_mail_thread" as "is_mail_thread","ir_model"...


I didn't look further into what the problem was, seeing this error I concluded that there was a dependency on the mail module.
By adding this dependency it works (tm)

But I can take a closer look if you prefer.

**Comment by maisim** [comment]
That said, I find the dependency rather logical (not annoying) because most creations are logged via the mail module.

**Comment by thomaspaulb** [comment]
Do you still have the traceback that was posted around the error?

**Pull request closed without merging**
