### PR TITLE
[14.0][ADD] base_tier_validation_report

### PR DESCRIPTION
**Pull request by kittiu**
This module add a simple report for user to see history of his reviews.

Q: should this be included in base_tier_validation?

image

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM. 

It is fine in a new module. But it is true that we're starting to have a lot of sub-modules, maybe it is worth to add a tier validations settings panel to control the installation of extra features/modules.

**Comment by kittiu** [comment]
> panel

Same here, I was thinking about this too :). I can help doing it in base_tier_validation.

**Comment by kittiu** [comment]
> LGTM.
> 
> It is fine in a new module. But it is true that we're starting to have a lot of sub-modules, maybe it is worth to add a tier validations settings panel to control the installation of extra features/modules.

@LoisRForgeFlow here you go, https://github.com/OCA/server-ux/pull/405

**Review by fshah-initos — APPROVED** [review]
Code review and functional tests.
Looks good to me.

**Comment by kittiu** [comment]
Is this ok for merge?

**Review by hitrosol — APPROVED** [review]
Functional review, LGTM

**Review by marcelsavegnago — APPROVED** [review]

**Comment by kittiu** [comment]
Error message, ERROR: No matching distribution found for odoo_test_helper

`odoo_test_helper` already exists in test requirement. Anyone knows what problem is?

**Pull request merged**
