### PR TITLE
[17.0][PORT] 699 from 14.0: base_tier_validation multiple comment with approve_sequence_bypass

### PR DESCRIPTION
**Pull request by bosd**
Port #699 from 14.0 to 17.0.

when option approve_sequence_bypass is enabled and comments option with
sequence, the user add a comment and all level add this
comment.
This code add comment only for appropriate tier validation

### CODE REVIEW

**Comment by bosd** [comment]
Let's first merge #800 before continiung working on this one.

**Review by Dranyel-Bosd — APPROVED** [review]
LGTM :+1:  :100:

**Comment by bosd** [comment]
@celm1990 Can you please review?

**Review by LoisRForgeFlow — COMMENTED** [review]
It is not strictly a forward port, as you have done a similar change but not the same. Could you explain why? Thanks!

**Comment by bosd** [comment]
Superseeded by #905

**Pull request closed without merging**
