### PR TITLE
[14.0] [mig] sequence_reset_period

### PR DESCRIPTION
**Pull request by schhatbar-initos**

### CODE REVIEW

**Comment by schhatbar-initos** [comment]
@ps-tubtim Can you please review this PR?

**Review by etobella — APPROVED** [review]
No major changes

**Review by fshah-initos — APPROVED** [review]
Functional Review done

**Comment by schhatbar-initos** [comment]
@simahawk Is it possible to merge this PR now hence it is approved?

**Review by ps-tubtim — APPROVED** [review]

**Comment by schhatbar-initos** [comment]
@etobella Is it possible to merge this PR now hence it is approved?

**Comment by etobella** [comment]
Sure, but I don't have the power. Let's check if some @OCA/tools-maintainers can call the runbot :smile:

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
