### PR TITLE
10.0 mig date range

### PR DESCRIPTION
**Pull request by daramousk**

### CODE REVIEW

**Comment by astirpe** [comment]
It's already existing for V10, here: https://github.com/OCA/server-tools/tree/10.0

**Comment by lmignon** [comment]
@daramousk Thank you for this PR. Nevertheless this addon already exists in odoo 10 but in an other repo https://github.com/OCA/server-tools/tree/10.0/date_range

**Comment by daramousk** [comment]
Ah thank you, totally missed it.

**Comment by lmignon** [comment]
you're welcome @daramousk :smirk:

**Pull request closed without merging**
