### PR TITLE
[MIG][14.0] base_import_security_group Module

### PR DESCRIPTION
**Pull request by Murtaza-OSI**

### CODE REVIEW

**Comment by dreispt** [comment]
@Murtaza-OSI Tests are failing, can you check please?

**Comment by dreispt** [comment]
@Murtaza-OSI can you please check the failing test?

**Comment by dreispt** [comment]
@chandresh-OSI can you fix Travis please?

**Comment by Chandresh-OSI** [comment]
Okay, I will work on it.

**Comment by dreispt** [comment]
@murtuzasaleh @Chandresh-OSI Can we push this to the finish line please?

**Comment by dreispt** [comment]
@Murtaza-OSI

**Comment by StefanRijnhart** [comment]
Tests are fixed in 13.0 by the refactoring by @victoralmau in https://github.com/OCA/server-ux/pull/336/commits/acd0856518fa38ad3a7912f862a445b71c29d6fb#diff-cc1cb0a01a14febcb47183a19b4ab6340b2873d2b0b93d173465c8cfc2039ef8
so maybe you can redo the git-format-patch process to get a working Travis here.

**Comment by Chandresh-OSI** [comment]
Superseded by #342

**Pull request closed without merging**
