### PR TITLE
[17.0][MIG] base_tier_validation: Migration to 17.0

### PR DESCRIPTION
**Pull request by moitabenfdz**

### CODE REVIEW

**Comment by Duranio** [comment]
@moitabenfdz Please, could you tell me why this PR is marked as draft and how long will it take to be ready for review?

**Comment by bosd** [comment]
I would like to open the discussion.
What do you think of merging base_tier_validation_waiting Into the base module for v17?

Imo it would simplify the code.

**Comment by moitabenfdz** [comment]
> @moitabenfdz Please, could you tell me why this PR is marked as draft and how long will it take to be ready for review?

I have found problems with the JS files. I don't know how long it will take me to fix them, as I have no experience with Odoo JS.

**Comment by TonyMasciI** [comment]
> > @moitabenfdz Please, could you tell me why this PR is marked as draft and how long will it take to be ready for review?
> 
> I have found problems with the JS files. I don't know how long it will take me to fix them, as I have no experience with Odoo JS.

Hi @moitabenfdz , can you share the errors with us?

**Comment by moitabenfdz** [comment]
@TonyMasciI you can check them in the runboat. I didn't migrate JS files, and a lot of things in mail are changed from v16 to v17.

**Comment by bosd** [comment]
Additionally, before merging, please update this pr, to include the latest commits on V16.

**Comment by pedrobaeza** [comment]
Please squash administrative commits, as 448 commits seems a lot.

**Comment by bosd** [comment]
> What do you think of merging base_tier_validation_waiting Into the base module for v17?

@moitabenfdz
What is your opinion about including this base functionality into the core module?

**Comment by celm1990** [comment]
@moitabenfdz can you update the is status of this PR please, I interested on this module is migrated to V17, could you comment if I can continue migration if necessary

**Pull request closed without merging**
