### PR TITLE
[15.0][IMP] base_tier_validation: Allow define fields that is allowed modify under validation process as system parameters.

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa  TT49995

ping @CarlosRoca13 @chienandalu

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Hi @sergio-teruel 

You might be interested on checking the latest improvement in v16 called "exceptions" https://github.com/OCA/server-ux/pull/902. It is fully configurable and there is also an ongoing improvement to allow to define exceptions based on security groups https://github.com/OCA/server-ux/pull/915.

Backporting it to v15 might be a good option for you.

**Comment by sergio-teruel** [comment]
Hi @LoisRForgeFlow 
I've been checking and I see that I need more commits since 16.0. So at this point I'll leave it at that since this won't be carried over to later releases.

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
@sergio-teruel Ok, as you prefer. I will submit a blocking review to remember that this won't ever be merged as it diverges from the main line followed in newer versions that can at some point be backported.

**Comment by sergio-teruel** [comment]
Ok. Don't worry .. I close this PR and I fix in private module.

**Pull request closed without merging**
