### PR TITLE
[12.0][MIG] base_tier_validation_forward

### PR DESCRIPTION
**Pull request by MateuGForgeFlow**
Backport from v13.
cc @AdriaGForgeFlow @LoisRForgeFlow

### CODE REVIEW

**Review by AdriaGForgeFlow — APPROVED** [review]
Functional review LGTM :+1:

**Review by JoanSForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza can you merge this one?

**Pull request merged**
