### PR TITLE
[11.0][IMP] base_tier_validation module

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
This PR intends to make some improvements on base_tier_validation module:
* The review information is now available between the form and the chatter in a collapse object:
image
image

In order for the new widget to appear correctly some changes need to be done in the modules that inherit from this one. (This will be done in new PRs in the corresponding repositories)
Replace this:
```
<div name="button_box" position="inside">
    <field name="review_ids" widget="review_popup" attrs="{'invisible':[('review_ids', '=', [])]}"/>
</div>
```
With this:
```
<xpath expr="//form/div[hasclass('oe_chatter')]" position="before">
    <field name="review_ids" widget="tier_validation" attrs="{'invisible':[('review_ids', '=', [])]}"/>
</xpath>
```

cc ~ @Eficent @lreficent @etobella

### CODE REVIEW

**Review by JordiBForgeFlow — APPROVED** [review]
I think it's a great addition!

**Review by rousseldenis — APPROVED** [review]

**Review by etobella — APPROVED** [review]
Great addition!

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Review by LoisRForgeFlow — COMMENTED** [review]
small comment:

image

**Comment by rousseldenis** [comment]
@jbeficent Time to test the '/ocabot merge' command!

**Comment by sbidoul** [comment]
@rousseldenis There can be other text in the command, but the command must be alone on its line. Also don't forget to use patch|minor|major to bump version.

**Comment by rousseldenis** [comment]
> @rousseldenis There can be other text in the command, but the command must be alone on its line. Also don't forget to use patch|minor|major to bump version.

I know, it was just a ping as I've no merge right access.

**Pull request closed without merging**
