### PR TITLE
[MIG] date_range: Migrate to version 17.0

### PR DESCRIPTION
**Pull request by sonhd91**
Based on: 
* https://github.com/ramiadavid/server-ux/tree/17.0-mig-date_range

Note:
* fixed issue `active` fields feature doesn't worked on `date.range.types` (doesn't hide it on search view when `active` set `False`)

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Review by gurneyalex — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Wrong readme fragment defining 2 times an image with the same name it seems. Not sure if something of the automatic conversion or copy/paste thing.

**Comment by sonhd91** [comment]
> Wrong readme fragment defining 2 times an image with the same name it seems. Not sure if something of the automatic conversion or copy/paste thing.

I just updated image name to avoid duplicate subname error

**Pull request merged**
