### PR TITLE
[16.0] [MIG] base export manager

### PR DESCRIPTION
**Pull request by syera94**
@bealdav @florian-dacosta could you check this PR, thanks in advance guys

### CODE REVIEW

**Review by florian-dacosta — APPROVED** [review]

**Comment by JoelZilli** [comment]
@syera94 Hello, it seems that the runbot instance for this PR is not working. Could you please check that so i can do a functional test? Thanks!

**Comment by pedrobaeza** [comment]
There's a general problem right now with runboat. Nothing particular about this PR. Please wait until the voluntary maintainers of OCA infrastructure are able to tackle it. Meanwhile, you can do a local test.

**Comment by JoelZilli** [comment]
@pedrobaeza Hello, any news about the status of runbot?

**Comment by pedrobaeza** [comment]
Rebasing this PR should now launch correctly the runboat.

**Comment by florian-dacosta** [comment]
@JoelZilli Seems all fine now

**Review by bruno-zanotti — APPROVED** [review]
Technical review LGTM

**Comment by kikopeiro** [comment]
Here's what I tried:

- I changed the configuration for the res.partner.category accesses (all accesses)
- I still can access the export option over this model
- Tested with not admin user

Did I miss something? V15 is working fine

What is reproduced is similar to what was discussed in this issue https://github.com/OCA/server-ux/issues/474.

**Comment by kikopeiro** [comment]
@syera94 Am I wrong? Thanks!

**Comment by liebana** [comment]
As @kikopeiro said, something is not ok here or I don't know if I'm testing it as I'm supposed to @syera94  cc @bealdav @florian-dacosta

**Comment by DorianMAG** [comment]
Hi @syera94 .
Thx for this work !
Any news about PR validate?

**Comment by flotho** [comment]
Runboat seems stucked @DorianMAG , please superseed this PR so that we'll be able to pass the CI/CD process

**Comment by pedrobaeza** [comment]
Superseded by #702

**Pull request closed without merging**
