### PR TITLE
[12.0][IMP] base_tier_validation: add details to error message

### PR DESCRIPTION
**Pull request by astirpe**
This would be helpful to understand the reasons of why an error occurs.

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@astirpe What is the aim of this? I don't see much value on showing technical names of fields to users. If you need this information, maybe is better if you debug your use case to see why is not working as expected, don't you think?

EDIT: Another option is that the message is only extended when the debug mode is active. WDYT? What concerns me is that this is an informative error that happens often (it is the main point of it, to block modification of records under validation), so for me it is not an application error where you show a technical trace.

**Comment by astirpe** [comment]
@LoisRForgeFlow I agree with you but we have an issue: https://github.com/OCA/account-invoicing/pull/871#issuecomment-791228153 and this kind of error could potentially occur with every module that extends the validation of an invoice. I didn't have a better solution for spotting which field is being written. Notice that the users who are entering a vendor bill are usually not so technical.

**Comment by LoisRForgeFlow** [comment]
> Another option is that the message is only extended when the debug mode is active. WDYT?

what about this? or you can use the display string of the fields?

**Comment by kittiu** [comment]
To me, I also don't see much use. The current message already fulfilled that nothing can be modified.

**Comment by astirpe** [comment]
@LoisRForgeFlow I now display the list of fields when user belongs to group "Technical Features" and I display the field string name instead of the technical name. Thanks!

**Comment by LoisRForgeFlow** [comment]
I have reviewd, I still see the a technical name:

image

**Comment by astirpe** [comment]
@LoisRForgeFlow  You are right, was my mistake! Should be working now.

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks!

**Pull request merged**
