### PR TITLE
[15.0][FIX] announcement: allow multicompany tags

### PR DESCRIPTION
**Pull request by chienandalu**
Allow users to share tags across companies (the access rule is already prepared for it)

cc @Tecnativa TT46715

please review @pedrobaeza @pilarvargas-tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by pilarvargas-tecnativa — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Oh, wait, @chienandalu, let's do it non filled by default (the same mood than partners and products).

**Comment by chienandalu** [comment]
Done

**Pull request merged**
