### PR TITLE
[15.0][MIG] base_user_locale

### PR DESCRIPTION
**Pull request by ChrisOForgeFlow**
Standard Migration
@ForgeFlow

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@ChrisOForgeFlow may I ask you to include also 4ce86c77adaff0612dc9cfc17026f25e856c4cdf ?

**Comment by alexey-pelykh** [comment]
And squash last two commits so that migration is done within one commit as per guidelines

**Comment by ChrisOForgeFlow** [comment]
@alexey-pelykh is done, thanks!

**Review by alexey-pelykh — APPROVED** [review]

**Comment by JuanyDForgeflow** [comment]
@ChrisOForgeFlow please rebase, runboat isn't working

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
It does not work in my functional test on runboat:

image

image

Do I miss something?

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
@LoisRForgeFlow Please follow the instructions in https://github.com/OCA/server-ux/pull/780 to test

**Comment by LoisRForgeFlow** [comment]
> @LoisRForgeFlow Please follow the instructions in #780 to test

Thanks!

**Review by LoisRForgeFlow — APPROVED** [review]
Testing in a incognito window did the trick and I was able to validate the functionality

LGTM

/ocabot merge nobump

**Pull request merged**
