### PR TITLE
Switch CI to GitHub actions

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by sbidoul** [comment]
Blocked on a dev status compatibility issue:
image

**Comment by sbidoul** [comment]
@etobella @simahawk either we downgrade document_quick_access_folder_auto_classification to Alpha or we upgrade edi_storage_oca to Beta.

**Comment by etobella** [comment]
Upgrade edi storage is fine for me, at the end it has been marked as beta on 15

**Comment by alexey-pelykh** [comment]
https://github.com/OCA/edi/pull/626

**Comment by simahawk** [comment]
EDI PR merged

**Comment by etobella** [comment]
@sbidoul Can you rebase in order to execute again the tests?

**Comment by simahawk** [comment]
```
2022-08-28 10:09:32,052 274 ERROR odoo odoo.addons.document_quick_access_folder_auto_classification.tests.test_document_quick_access_auto_classification: ERROR: TestDocumentQuickAccessClassification.test_ok_pdf
Traceback (most recent call last):
  File "/opt/odoo/odoo/tools/misc.py", line 849, in deco
    return func(*args, **kwargs)
  File "/__w/server-ux/server-ux/document_quick_access_folder_auto_classification/tests/test_document_quick_access_auto_classification.py", line 112, in test_ok_pdf
    "odoo.addons.document_quick_access_folder_auto_classification."
  File "/opt/odoo-venv/lib/python3.6/site-packages/mock/mock.py", line 1414, in __enter__
    original, local = self.get_original()
  File "/opt/odoo-venv/lib/python3.6/site-packages/mock/mock.py", line 1388, in get_original
    "%s does not have the attribute %r" % (target, name)
AttributeError: <module 'odoo.addons.document_quick_access_folder_auto_classification.components.document_quick_access_process' from '/__w/server-ux/server-ux/document_quick_access_folder_auto_classification/components/document_quick_access_process.py'> does not have the attribute 'decode'
```
https://github.com/OCA/server-ux/runs/8056833401?check_suite_focus=true#step:8:448

**Pull request closed without merging**
