### PR TITLE
[12.0][FIX] improve perf and solve compatibility with base_jsonify

### PR DESCRIPTION
**Pull request by sebastienbeau**
# Issue

Installing shopinvader (depend of base_jsonify) break if we install it after base_export_manager

# Details and solution

The inverse method on the name set the value of field1_id, field2_id...
As the name depend of the field1_id, field2_id we pass in the
_compute_name everytime we set one field and it's useless.

This generate the compatibility issue with base_jsonify and
shopinvader (and possibility other module) as the name computed
can be a dependency of other field.

For example (with base_jsonify) if I configure an ir.exports.line with
- name : "country_id/name"
- alias : country_id:countries/name

As the name is recomputed when we set the field1_id to "country_id" we
will have a name with the value "country_id" instead of
"country_id/name" and this do not match the alias and raise an error

Recomputing at the end of the inverse_name improve the perf and solve
the issue

@lmignon

### CODE REVIEW

**Comment by sebastienbeau** [comment]
@hparfr @rousseldenis @Yajo @pedrobaeza

**Comment by pedrobaeza** [comment]
Is there a way to exercise the problem in a test?

**Review by lmignon — APPROVED** [review]
@sebastienbeau All this makes sense. Not sure the performance gain will boost the application but at least your changes will replace 4 potential calls to `_compute_name(self):` by a unique call. (regardless of the depth of the path expressed by the name), Moreover, IMO, it also ensure the atomicity the `compute_name`. This method is designed to work with a fully initialised record. Before your change, since all the `fieldx_id` was reset at once and thereafter assigned one by one means that the `compute_name` was not called with all the required information until all values have been assigned to the fieldx_id.

**Review by rousseldenis — APPROVED** [review]
Makes sense to me

**Comment by rousseldenis** [comment]
@len-foss this can be in your interest

**Comment by simahawk** [comment]
@sebastienbeau any test to update?

**Pull request merged**
