### PR TITLE
[16.0][MIG] base_user_locale

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Standard migration, using https://github.com/OCA/server-ux/pull/471 as a reference

How was tested:

1. Make sure that you test with incognito mode in your browser, because it seems that the locale settings are stored in the browser's cache

2. Introduce the new locale settings in the config:
Using English (US) as base language, I override the locale into EU standard format:

image

3. Test
When creating a sales order I can see that the new format is used:

image

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@LoisRForgeFlow @JordiMForgeFlow FYI

**Review by JordiMForgeFlow — APPROVED** [review]
functional review 👍🏼

**Review by LoisRForgeFlow — APPROVED** [review]
Tested locally, LGTM

**Pull request merged**
