### PR TITLE
[16.0][MIG] document_quick_access: Migration to 16.0  

### PR DESCRIPTION
**Pull request by peluko00**

### CODE REVIEW

**Comment by peluko00** [comment]
Module migrated to version 16.0

cc https://github.com/APSL 148783

@miquelalzanillas @lbarry-apsl @Javierbcn @mpascuall please review

Issue https://github.com/OCA/server-ux/issues/534

**Review by mpascuall — APPROVED** [review]
Works correctly, checked in runboat

**Review by javierobcn — APPROVED** [review]
Works well in runboat

**Review by lbarry-apsl — APPROVED** [review]
Works, tested on Runboat

**Review by etobella — APPROVED** [review]
Functional and technical review

Thanks for the migration.

/ocabot merge nobump

**Pull request merged**
