### PR TITLE
[ADD]mass_editing:Added new 'copy from another field' functionality.

### PR DESCRIPTION
**Pull request by Trivedi-Vacha-SerpentCS**
New Functionality is added.
* User and copy the value from one field to another field.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check Travis

**Review by JayVora-SerpentCS — APPROVED** [review]

**Comment by JayVora-SerpentCS** [comment]
@pedrobaeza there many requests for v11 of massediting. Would you please push this repo on Odoo Appstore for v11 ? server-tools doesnt hve the module.

**Comment by vdewulf** [comment]
I tested on my local PC with v11 Community, but I have bad news :-(
Here are my test steps :

    Using the branch 11.0 without your fix
        I created a new mass editing rule for Contact -> Followers and added the Side Button
        I went to Contacts and followed 2 contacts as admin
        I selected both contacts and used the mass editing action to remove all the followers
        there are no errors but both contact still have admin as follower
        => this is "expected" as it was the issue I found out and wrote you about.
    I switched to your branch : https://github.com/OCA/server-ux/pull/19/files
        I created a new mass editing rule for Contact, but I got directly an error when I wanted to select the attributes of contact by clicking on "Add an item". Then I got this error: 
Odoo Server Error

Traceback (most recent call last):
  File "/home/virginie/eleven-odoo-dev/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/virginie/eleven-odoo-dev/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/virginie/eleven-odoo-dev/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/virginie/eleven-odoo-dev/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/virginie/eleven-odoo-dev/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/virginie/eleven-odoo-dev/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/virginie/eleven-odoo-dev/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/virginie/eleven-odoo-dev/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/virginie/eleven-odoo-dev/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/virginie/eleven-odoo-dev/odoo/addons/web/controllers/main.py", line 873, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/home/virginie/eleven-odoo-dev/odoo/addons/web/controllers/main.py", line 895, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/home/virginie/eleven-odoo-dev/odoo/odoo/models.py", line 4218, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/home/virginie/eleven-odoo-dev/server-ux/mass_editing/models/ir_model_fields.py", line 27, in search
    count=count)
  File "/home/virginie/eleven-odoo-dev/odoo/odoo/models.py", line 1480, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/virginie/eleven-odoo-dev/odoo/odoo/models.py", line 3769, in _search
    query = self._where_calc(args)
  File "/home/virginie/eleven-odoo-dev/odoo/odoo/models.py", line 3564, in _where_calc
    e = expression.expression(domain, self)
  File "/home/virginie/eleven-odoo-dev/odoo/odoo/osv/expression.py", line 668, in __init__
    self.parse()
  File "/home/virginie/eleven-odoo-dev/odoo/odoo/osv/expression.py", line 846, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'mass_editing_domain' in leaf "<osv.ExtendedLeaf: ('mass_editing_domain', 'in', '[77]') on ir_model_fields (ctx: )>"

**Comment by JayVora-SerpentCS** [comment]
@Trivedi-Vacha-SerpentCS

**Review by legalsylvain — CHANGES_REQUESTED** [review]
- Don't understand why you introduced various images. (serpentCS image, facebook, instagram ?)
- conflict should be solved.

thanks !

**Pull request closed without merging**
