### PR TITLE
[15.0][FIX] date_range: Allow select date_ranges on custom filters

### PR DESCRIPTION
**Pull request by CarlosRoca13**
This commit solves the problems reported on Issue https://github.com/OCA/server-ux/issues/597

cc @Tecnativa TT43442

ping @pedrobaeza @sergio-teruel 

I tried to set the description provided on the date_range but it needs to overwrite the onApply method with not a simply way to do it. As the description shows the range you are filtering by, I don't think this is a very important feature to keep.

### CODE REVIEW

**Review by sergio-teruel — APPROVED** [review]
Great!! @CarlosRoca13 

Thanks!!!

**Review by lmignon — APPROVED** [review]
Thank you for the fix @CarlosRoca13 LGTM (Code + functional)

**Comment by pedrobaeza** [comment]
@CarlosRoca13 one thing: I did the range from 2023-01-01 to 2023-12-31. Why it puts the next day on the filter?

Selección_019

**Comment by pedrobaeza** [comment]
And please fw-port it to v16.

**Comment by CarlosRoca13** [comment]
> 2023-01-01 to 2023-12-31

image

I can't reproduce it...

**Comment by pedrobaeza** [comment]
OK, it seems my fault.

**Pull request merged**
