### PR TITLE
[15.0] [MIG] document_quick_access_folder_auto_classification

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration
@ForgeFlow

Depends on:
https://github.com/OCA/server-ux/pull/443
https://github.com/OCA/edi/pull/491

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Fix development status issue: https://github.com/OCA/edi/pull/560

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by etobella — APPROVED** [review]
LGTM

**Pull request merged**
