### PR TITLE
[14.0][REF] document_quick_access_folder_auto_classification: Add dependenc…

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
…y on storage and edi

Forward port of https://github.com/OCA/server-ux/pull/323

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Comment by etobella** [comment]
Can you keep commit history?

**Comment by LoisRForgeFlow** [comment]
> Can you keep commit history?

Fixed!

**Review by etobella — APPROVED** [review]

**Pull request merged**
