### PR TITLE
[13.0][FIX] base_tier_validation: All models are visible when create a new definition

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT23936
This fix https://github.com/OCA/sale-workflow/pull/1152#issuecomment-633880654

@HaraldPanten Can you reviw??

### CODE REVIEW

**Review by HaraldPanten — CHANGES_REQUESTED** [review]
Hi @sergio-teruel ,

I'm afraid tests should be correctly adjusted.

**Comment by sergio-teruel** [comment]
@HaraldPanten onchange method removed from tests

**Review by HviorForgeFlow — APPROVED** [review]
:+1:

**Review by HaraldPanten — APPROVED** [review]
LGTM. 👍

**Review by ValentinVinagre — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
Tested locally

Thanks

**Review by AdriaGForgeFlow — APPROVED** [review]

**Pull request merged**
