### PR TITLE
[15.0][MIG] mass_operation_abstract

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by legalsylvain** [comment]
why do you migrate this module ?

**Comment by MiquelRForgeFlow** [comment]
Why not? It was on my list of modules to migrate.

**Comment by legalsylvain** [comment]
> Why not? It was on my list of modules to migrate.

;-). Well, that module doesn't do anything but is usefull as a dependency. my question is for which module ? Note : AFAIK, this module is obsolete for V16. (But I don't know for V15).

**Comment by LoisRForgeFlow** [comment]
Indeed, this migration is not needed, see https://github.com/OCA/server-ux/pull/472#issuecomment-1185593749.

**Comment by MiquelRForgeFlow** [comment]
Nice

**Pull request closed without merging**
