### PR TITLE
[16.0][MIG] base_tier_validation_formula

### PR DESCRIPTION
**Pull request by anothingguy**
- the code in v15 works well in v16. This PR just changed a depreciated `invalidate_cache` method to `invalidate_recordset` method in test case

### CODE REVIEW

**Comment by yankinmax** [comment]
@anothingguy pls rebase on the latest 16.0 updates. pre-commit should be fixed now

**Review by yankinmax — APPROVED** [review]

**Comment by yankinmax** [comment]
@anothingguy ping

**Review by santostelmo — APPROVED** [review]

**Review by simahawk — APPROVED** [review]
LG

**Comment by simahawk** [comment]
closing in favor of #606  to speed it up

**Pull request closed without merging**
