### PR TITLE
[16.0][MIG] base_tier_validation_waiting

### PR DESCRIPTION
**Pull request by bosd**
Standard migration using odoo-module-migrator /ocabot migration base_tier_validation_waiting .
depends on:
#747
#749  
#766
#767 (test temp disabled)
#769 
#770

### CODE REVIEW

**Comment by bosd** [comment]
Dropped the dependency & tests on the posting of double messages.. Now we finally have green tests ✔️
✨ 🎉

**Comment by bosd** [comment]
@BT-jcolmeiro This is a module you know :smile: 
Can you please review? :pray:

**Review by Dranyel-Bosd — APPROVED** [review]
LGTM :+1:

**Comment by bosd** [comment]
@dreispt Can you please review 🙏

**Review by dreispt — APPROVED** [review]

**Pull request merged**
