### PR TITLE
[13.0][MIG] sequence_reset_period

### PR DESCRIPTION
**Pull request by ps-tubtim**
Standard migration.

### CODE REVIEW

**Review by etobella — APPROVED** [review]
Great!! No major changes.

**Review by HaraldPanten — APPROVED** [review]
LGTM. Functional review 👍

**Review by ivantodorovich — APPROVED** [review]
LGTM

**Review by Saran440 — APPROVED** [review]
LGTM :+1:

**Comment by ps-tubtim** [comment]
@OCA/tools-maintainers Could you merge this PR?

**Review by jarroyomorales — APPROVED** [review]
LGTM

**Pull request merged**
