### PR TITLE
[13.0][IMP] base_tier_validation_formula

### PR DESCRIPTION
**Pull request by ps-tubtim**
Cherry-pick from https://github.com/OCA/server-ux/pull/116

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

Thanks!

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Comment by LoisRForgeFlow** [comment]
I cancelled the merge because I just realized one thing: one of the commits is full of conlicts (probably of a cherry-pick) and the other is just fixing them, plus they have the same commit msg. I think it is not justified to have both commits, can you just squash them together?

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
until commits are squashed (the first one intrudoced git-operation-generated conflicts ans second just fixed them, this should have been done in the operation and resulting in one clean commit)

**Comment by HviorForgeFlow** [comment]
@ps-tubtim it seems bb6d3db still having HEADs. A way to solve it would be to squash both commits into one called ```[IMP] base_tier_validation_formula: Allow use both domain and formula in tier definitions``` for example, personally, I don't like to use version number on imp or fix commits then other contributors can cherry-pick them without change commit name.

**Comment by LoisRForgeFlow** [comment]
Thanks, ready to merge:

/ocabot merge minor

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
