### PR TITLE
[13.0][FIX] document_quick_access_folder_auto_classification: remove dead code

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Since the refactor to use edi_storage capabilities the cron is not needed
because the EDI and EDI backend crons do the job of retrieving the files
and create the exchange records to process and create the jobs to
process them. Actually the cron job in this module is failling in most of
the cases because it is using the storage "home" path instaed of the
input path.

cc @etobella 

@ForgeFlow

### CODE REVIEW

**Review by etobella — APPROVED** [review]

**Comment by etobella** [comment]
You probably need to remove the tests....

**Comment by LoisRForgeFlow** [comment]
@etobella better late than never, tests are reworked :)

**Review by JoanSForgeFlow — APPROVED** [review]
LGTM! :+1:

**Pull request merged**
