### PR TITLE
[FIX] [16.0] base_tier_validation: Tier Validation Exceptions

### PR DESCRIPTION
**Pull request by Shide**
Add Fields Exceptions that allows certain fields can be modified during the validation process, after the validation process or in both cases.

https://www.loom.com/share/f684c7672d534e4d91f4e3cadc5ce1ee?sid=44e7eb31-0a71-4ec0-a8fa-dd589abeac8a

MT-6609 @moduon @yajo @rafaelbn @EmilioPascual @fcvalgar @Gelojr @LoisRForgeFlow please review if you want :)

### CODE REVIEW

**Review by Gelojr — APPROVED** [review]
Nice job @Shide Your video makes it very clear
Thanks

**Review by fcvalgar — APPROVED** [review]
Functional review,

LGTM, thank you @Shide

**Review by rafaelbn — APPROVED** [review]
It looks great! Nice video! ❤️ 

> https://www.loom.com/share/f684c7672d534e4d91f4e3cadc5ce1ee?sid=44e7eb31-0a71-4ec0-a8fa-dd589abeac8a

We would appreciate @LoisRForgeFlow review 😄 🙏🏼 

Thank you!

**Review by LoisRForgeFlow — APPROVED** [review]
I think this block was an unexpected outcome of https://github.com/OCA/server-ux/pull/860#pullrequestreview-2073201756.

The idea behind the original change was legit: why would you allow to modify any record once it is validated? If you allow to do so, the validation loses a bit of its purpose.

But it was too restrictive and I agree that there are exceptions. Your proposal addresses that in a good and extensible way so :+1: from my side.

BTW, Thanks for taking the time to explain in a video :1st_place_medal:

**Pull request merged**
