### PR TITLE
[FIX] use more robust ready indicator

### PR DESCRIPTION
**Pull request by hbrunn**
this should avoid timing issues during tests

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
To have this fixed would be wonderful. Why does this work better?

**Comment by hbrunn** [comment]
jQuery returns an empty jQuery collection, but it's still an object, which when cast to boolean is true. In JS, also the empty object is still an object:

```javascript
> Boolean({})
true
```

**Review by StefanRijnhart — APPROVED** [review]
Great, thanks!

**Comment by StefanRijnhart** [comment]
Superseded by https://github.com/OCA/server-ux/pull/341

**Pull request closed without merging**
