### PR TITLE
[12.0][MIG] subscription from the official addons of Odoo Community v10 to OCA

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by sbidoul** [comment]
Hi @alexis-via 

Could you do an initial commit that takes the Odoo SA code as is, and then another commit with your changes, to avoid any doubt about copyright attribution

Perhaps this module should be renamed to `recurring_document` or something, to avoid confusion with the OE subscription modules?

**Comment by pedrobaeza** [comment]
And why in server-ux?

**Comment by alexis-via** [comment]
@pedrobaeza feel free to suggest a better project and I'll create another PR.

**Comment by pedrobaeza** [comment]
on OCA/contract?

**Comment by alexis-via** [comment]
OK

**Pull request closed without merging**
