### PR TITLE
[15.0][MIG] base_revision

### PR DESCRIPTION
**Pull request by jwaes**

### CODE REVIEW

**Comment by jwaes** [comment]
I don't understand. I just added a few extra test lines and now all 4 checks fail ?

**Comment by jwaes** [comment]
https://github.com/OCA/sale-workflow/pull/1931
depends on this

**Comment by JasminSForgeFlow** [comment]
Hi @jwaes,

Can you please squash commits and keep only one for migration code?

Thanks

**Comment by jwaes** [comment]
> Can you please squash commits and keep only one for migration code?

i tried 'something', but not sure it is correct :-(

**Comment by ao-landoo** [comment]
@jwaes Could you try to squash the commits correctly so we can move forward?

**Comment by leemannd** [comment]
Base work seems legit. I'm currently testing it.
@jwaes all commits after the one doing the migration could be sqashed together. https://github.com/OCA/server-ux/pull/456/commits/8195bd950f7c6979efa343ae0f481545b1fb4e4b

You'll find here a documentation to help you -> https://www.git-tower.com/learn/git/faq/git-squash

**Comment by ao-landoo** [comment]
Continues on #522 as no activity

**Review by leemannd — COMMENTED** [review]
Works well, but commits needs reworks

**Pull request closed without merging**
