### PR TITLE
[MIG] base_tier_validation_forward: Migration to 17.0

### PR DESCRIPTION
**Pull request by denaux**

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@denaux could you include this fix from 16.0 here https://github.com/OCA/server-ux/pull/930 ?

**Comment by denaux** [comment]
@LoisRForgeFlow thanks for the heads-up. I've included the fix.

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks! Code review LGTM

**Comment by bosd** [comment]
Code review, LGTM. 👍 
There is a warning message..

```
WARNING odoo odoo.addons.base.models.ir_model: Rule access.tier.validation.forward.wizard has no group, this is a deprecated feature. Every access-granting rule should specify a group. 

```

**Comment by denaux** [comment]
@bosd good catch. I've added the `base.group_user` to the rule in the security file.

**Review by bosd — APPROVED** [review]
Thanks!! LGTM 👍

**Pull request merged**
