### PR TITLE
[14.0][MIG] base_optional_quick_create

### PR DESCRIPTION
**Pull request by SimoRubi**
Standard migration from https://github.com/OCA/server-ux/commit/9bef3c430a911378c9abe950a0fb5eb36b440f8a

### CODE REVIEW

**Review by tafaRU — APPROVED** [review]

**Review by fshah-initos — APPROVED** [review]
LGTM.

**Comment by fshah-initos** [comment]
Please squash the last commits into migration commit.

**Comment by SimoRubi** [comment]
> Please squash the last commits into migration commit.

Thanks for the review! I squashed the fixup commit in migration commit.
I'd rather keep the last one separated in order to keep @kimirondon's authorship unless he/she agrees with losing authorship for that part (the added test)

**Comment by fshah-initos** [comment]
It seems that PR is ready for review It will be nice if anyone can merge it.

**Comment by kimirondon** [comment]
@SimoRubi thanks for keeping the authorship of the commit :)

**Comment by AaronHForgeFlow** [comment]
I am afraid I am not understanding the purpose of the module? After setting the models product.product and product.template as "Avoid Quick Create" I can still create them from a many2one field on runbot:

image

If the purpose of the module is a different one just let me know.

**Comment by SimoRubi** [comment]
> I am afraid I am not understanding the purpose of the module? After setting the models product.product and product.template as "Avoid Quick Create" I can still create them from a many2one field on runbot:
> 
> image
> 
> If the purpose of the module is a different one just let me know.

Thanks for having a look, the module avoids _under the hood_ creation of a record from the user interface by only specifying the name.
It sounds more complicated than it actually is, see below:
Peek 2021-04-15 10-35
Note that creation of 'not quick product' has to be done from the product's form while creation of 'quick product' happened _under the hood_; the only difference is the flag in product's model.

**Comment by AaronHForgeFlow** [comment]
all right, I see it now. Thanks a lot!

**Review by AaronHForgeFlow — APPROVED** [review]
Functional test

**Comment by youring** [comment]
AFAIK, here quick_create = Create in Odoo nomenclature
I think of a more straightforward name: base_force_create_to_create_and_edit.
Companion module that enhance the create or/and edit experiences: [web_m2x_options](https://github.com/OCA/web/tree/14.0/web_m2x_options)

**Comment by okuryan** [comment]
@pedrobaeza , I think it is ready to be merged. WHo can merge this PR into 14.0 ?

**Comment by pedrobaeza** [comment]
Look for the repository PSCs

**Comment by okuryan** [comment]
@LoisRForgeFlow , can you merge this PR?

**Comment by fshah-initos** [comment]
@all Can this be merged?

**Pull request merged**
