### PR TITLE
[17.0][IMP] base_tier_validation: add icon

### PR DESCRIPTION
**Pull request by AlexPForgeFlow**
Proposal of icon for Tier Validation

### CODE REVIEW

**Review by LoisRForgeFlow — COMMENTED** [review]
Can you reduce the blank space around the icon? Odoo automatically add border in the menu icons:

image

Also can you make sure that the image size is squared. Ideally 128x128 pixels (OCA icons) or 100x100 (Odoo 17 icons)

**Review by pedrobaeza — COMMENTED** [review]
Thanks for the improvement! The usual size is 140x140 though, and it would be great if you provide the source SVG for derivatives.

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Comment by pedrobaeza** [comment]
What about the SVG source?

**Comment by AlexPForgeFlow** [comment]
@pedrobaeza I don’t have the SVG source, I did it other way

**Comment by pedrobaeza** [comment]
OK, I have re-done it on SVG from your idea. Can you please include them? (the PNG has been re-exported from the SVG)

icon
icon

**Review by pedrobaeza — APPROVED** [review]
Thank you very much.

/ocabot merge patch

**Pull request merged**
