### PR TITLE
[13.0][FIX] base_tier_validation_formula: Fix cache miss error on iteration records

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

### CODE REVIEW

**Review by etobella — APPROVED** [review]
LGTM

**Review by victoralmau — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
I think this is not correct when no `definition_id.reviewer_expression` is defined, landing in this line: https://github.com/OCA/server-ux/pull/253/files#diff-e4429a6dfbf0c3b86048e58f796de3404a1b277811e7036f3502794460ff8303R50

You should assign them instead False

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza could you check if this is correct now?

**Review by pedrobaeza — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
@sergio-teruel could you forward port if needed?

**Pull request merged**
