### PR TITLE
[15.0][IMP] base_tier_validation: Add validation_status field to tier.validation

### PR DESCRIPTION
**Pull request by victoralmau**
FWP from 14.0: https://github.com/OCA/server-ux/pull/730

Add `validation_status` field to `tier.validation`

@Tecnativa TT33369

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Add here also the extra column with decoration for doing it in one shot.

**Comment by victoralmau** [comment]
> Add here also the extra column with decoration for doing it in one shot.

It is not possible to add the extra column here, the column is added to an abstract model that is inherited in others (`purchase.order` for example) and it is in those views specifically (if desired) where it has to be added.

**Comment by pedrobaeza** [comment]
I don't get the sense of the new commits.

**Comment by victoralmau** [comment]
> I don't get the sense of the new commits.

The latest commits are related to resolving the test error: https://github.com/OCA/server-ux/actions/runs/6623289456/job/17990083714#step:8:1520

**Review by pedrobaeza — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
