### PR TITLE
[15.0][IMP] announcement: add attachments field

### PR DESCRIPTION
**Pull request by pilarvargas-tecnativa**
A new field has been added to be able to attach files to the announcement, and these attachments will be displayed in the announcement notification modal.

image

Modal: 
image

cc @Tecnativa TT42581

@CarlosRoca13 @victoralmau please review :)

### CODE REVIEW

**Comment by CarlosRoca13** [comment]
Doing a test in runbot I found the following error:

1- We create a new Announcement
2- We assign it to Marc Demo and we add an attachment
3- Log in as Marc Demo
4- We can see an error on the screen

If you try to access the Announcement created via Discuss > Announcements you will see the same error.

In the following gif you can see an example
anuncio error

**Comment by pedrobaeza** [comment]
Pilar, try linking the attachment to the announcement (res_id and res_model fields).

**Comment by pilarvargas-tecnativa** [comment]
> try linking the attachment to the announcement (res_id and res_model fields)

The relationship of the attachments is m2m, the announcement is linked in the res_id and res_model fields of the attachments in addition to a table where the ids of the announcements and the ids of the attachments are stored. I don't understand why a user allowed in that announcement can't see it in case there are attachments. I have tried to rewrite the res_id field of attachments to add the ad model and this way they can be displayed, although it was a test since it is not correct.
I don't know how exactly I could link the attachments to the announcement with the fields you mention as it is an m2m.

**Review by chienandalu — APPROVED** [review]
Works like charm :) Thank you both :+1:

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge major

**Pull request merged**
