### PR TITLE
[17.0][IMP] base_tier_validation: Add reminder option

### PR DESCRIPTION
**Pull request by TDu**
Forward port from https://github.com/OCA/server-ux/pull/873

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Thanks @TDu 

The test are failing, and it is one of the new ones about the reminders, could you have a look?

**Comment by LoisRForgeFlow** [comment]
Hi @TDu 

Just a reminder for this reminder thing here  :laughing: 

It would be good to get this merged to align versions.

Thanks!!

**Comment by LoisRForgeFlow** [comment]
This patch it is likely also needed here https://github.com/OCA/server-ux/pull/960

**Comment by TDu** [comment]
> This patch it is likely also needed here #960

I think you meant #968 and it has been included

**Comment by TDu** [comment]
Closing, it will be ported in #968 where the test issue if fixed

**Pull request closed without merging**
