### PR TITLE
[16.0][MIG] mass_editing > server_action_mass_edit: Migration to 16.0

### PR DESCRIPTION
**Pull request by ramiadavid**
#534

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You're on fire migrating modules!

/ocabot migration mass_editing

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
I have tried on runboat and it seems to not be working.

- I have added an action to update the customer on the sales order: http://oca-server-ux-16-0-pr544-881fccad15d4.runboat.odoo-community.org/web?debug=1#cids=1&menu_id=4&action=8&model=ir.actions.server&view_type=form&id=319
- Added the contextual action
- Go to sales orders
- Select one and click on Action > Update customer
- Select other customer and Apply

And nothing happens.

**Comment by ramiadavid** [comment]
> I have tried on runboat and it seems to not be working.
> 
> * I have added an action to update the customer on the sales order: http://oca-server-ux-16-0-pr544-881fccad15d4.runboat.odoo-community.org/web?debug=1#cids=1&menu_id=4&action=8&model=ir.actions.server&view_type=form&id=319
> * Added the contextual action
> * Go to sales orders
> * Select one and click on Action > Update customer
> * Select other customer and Apply
> 
> And nothing happens.

Hi @pedrobaeza 

It works perfectly, but you also have to select the 'action' in the first field 'Set' or 'Remove', in Odoo16 there are fields that when they are empty it is hard to see that they are there

maybe it is better to put it as required?
image

**Comment by pedrobaeza** [comment]
Oh, what a mistake by my part! Anyway, 2 alternatives can be made:

- Make the field required, and then add a new selection value "Don't touch".
- When clicking on "Apply", if none of the fields is set, raise an error.

**Comment by pedrobaeza** [comment]
And other thing: why they don't appear in the same line, making the UI a bit more confusing?

**Comment by ramiadavid** [comment]
> Oh, what a mistake by my part! Anyway, 2 alternatives can be made:
> 
> * Make the field required, and then add a new selection value "Don't touch".
> * When clicking on "Apply", if none of the fields is set, raise an error.

I personally like the first one better.

**Comment by ramiadavid** [comment]
> And other thing: why they don't appear in the same line, making the UI a bit more confusing?

ok i'm going to put it on a line it will probably look better

**Comment by ramiadavid** [comment]
Hi @pedrobaeza 
I think this is better:

- Selection field: 
   - Added `Don't touch` option
   - Required
- Value field:
   - Invisible if selection is set to `Don't touch` or `Remove`
 
Two fields inline

**Comment by legalsylvain** [comment]
Hi. Could you take a look on https://github.com/OCA/server-ux/issues/539 ?
Thanks !

**Comment by legalsylvain** [comment]
> And nothing happens.

I think that if all lines are set to "Don't touch" a UserError should be raised when clicking on apply.

> in Odoo16 there are fields that when they are empty it is hard to see that they are there

agree ! ;-) Feel free to review https://github.com/OCA/web/pull/2317

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi regarding that topic https://github.com/OCA/server-ux/issues/539#issuecomment-1293435337

do you want to make the changes ? or do you want I do a PR against yours ? 

thanks !

**Comment by ramiadavid** [comment]
@legalsylvain 
As you prefer, I can make the changes if that is what you want

**Comment by legalsylvain** [comment]
>  As you prefer, I can make the changes if that is what you want

I can do it. (this is a request for homogenization on my part after all !)
Is your PR stable? because if I have to rename the module and the files, it will generate conflicts if you do it too.

**Comment by ramiadavid** [comment]
> > As you prefer, I can make the changes if that is what you want
> 
> I can do it. (this is a request for homogenization on my part after all !) Is your PR stable? because if I have to rename the module and the files, it will generate conflicts if you do it too.

Yes, you can rename whatever you want without problem

**Comment by legalsylvain** [comment]
Renaming done here https://github.com/ramiadavid/server-ux/pull/1 and ready for review.
Note : once merged, I'll do the according PR regarding the renaming in OCA/openupgrade project.

regards.

**Review by legalsylvain — APPROVED** [review]
thanks ! 

Note : (for another PR), I'd like to introduce group of fields in the wizard. Ex : product mass edit : 
- groups 1 : "prices" : standar_price, list_price, etc..
- groups 2 : "UoM & packaging" : uom_id, uom_po_id, etc...

I tried to use the widget note_and_section (used on sale order, purchase order, invoices, ...) without success. (and it generate an ugly dependency to ``account`` module).
So, I was thinking to add an optional column on the fields lines named "group_name". If set, it generate groups in the wizard. What do you think, regarding that features ?
I think that when there are a lot of fields, user can be a little lost in all the fields in the wizard Interface.

**Comment by legalsylvain** [comment]
@pedrobaeza : I think your remarks have been answered. Could you update your review ?

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Retrying after #551 

/ocabot merge nobump

**Review by leemannd — COMMENTED** [review]
Hello @ramiadavid , @pedrobaeza , @legalsylvain 

I'm wondering what is your opinion on the renaming of module. Shouldn't it be added also migration scripts to handle its renaming?
The question is intended to know if it's worth to spend the time to add them and propose to you a PR with it.

**Comment by pedrobaeza** [comment]
Already done: https://github.com/OCA/OpenUpgrade/blob/f29f99fe04fdbe4a014be71f5fc0095e3eadff5c/openupgrade_scripts/apriori.py#L24 and https://github.com/ramiadavid/server-ux/blob/e37159e9d3d1c884f11f642600e9e5f0379cb77b/server_action_mass_edit/migrations/16.0.2.0.0/pre-migration.py :wink:

**Comment by leemannd** [comment]
@pedrobaeza Thank you for the first link. I forgot to check in openupgrade :pray:

**Pull request merged**
