### PR TITLE
[16.0][MIG] base_optional_quick_create

### PR DESCRIPTION
**Pull request by baimont**
https://github.com/OCA/server-ux/issues/534

### CODE REVIEW

**Review by FrancoMaxime — APPROVED** [review]
LGTM

**Review by flotho — APPROVED** [review]
tested on runboat,
works as expected
LGTM
thanks

**Review by kakurai8 — APPROVED** [review]
I tested on my dev env, it works as expected.
LGTM.

**Review by adrienpeiffer — APPROVED** [review]

**Comment by adrienpeiffer** [comment]
@OCA/server-environment-maintainers Could you merge this one ?

**Pull request merged**
