### PR TITLE
[15.0][MIG] base_field_deprecated

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration of https://github.com/OCA/server-ux/pull/580.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Error in pre-commit unrelated to PR.

Selection_743

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM 👍🏽

**Pull request merged**
