### PR TITLE
[14.0][FIX] base_tier_validation: avoid errors after uninstalling tier validation support

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by kittiu** [comment]
I try to do user test, by install purchase_tier_validation, then start a purchase validaiton. Then, try to uninstall base_tier_validation.
I can't see the error. How to produce the error? @dreispt

**Comment by dreispt** [comment]
@kittiu You need to a Purchase with a pending approval request

**Comment by kittiu** [comment]
@dreispt I really try to replicate, but I couldn't see any error. I did following,

1. Install purchase_tier_validation
2. Create a tier and start validation on a PO

image

3. Uninstall base_tier_validation.

I don't see any error, even I open the console logs.

Can you elaborate more how to get into error?

**Comment by dreispt** [comment]
Superseded by #451

**Pull request closed without merging**
