### PR TITLE
[14.0][IMP] base_tier_validation, add tier description on stripe

### PR DESCRIPTION
**Pull request by kittiu**
The snippet in this enhancement is provided by @nmoturi, Thank you!

image

@nmoturi, by the way, as I tested it I found that the description will appear after a while, like 1 mins. Do you experience this too?

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
> @nmoturi, by the way, as I tested it I found that the description will appear after a while, like 1 mins. Do you experience this too?

Regarding this message it seems that this still needs more love/testing, I will mark the PR as work in progress.

Also, why don't you do this server side? i.e. add a computed field with the message and extend the template to use that field, at a first glance I don't anticipate problems and seems more clean and easy to unit-test than an ajax call.

**Comment by kittiu** [comment]
@LoisRForgeFlow you are right! It is much simpler :)

**Comment by nmoturi** [comment]
> @LoisRForgeFlow you are right! It is much simpler :)

Indeed, its much simpler and cleaner approach. Thanks @kittiu I see you had already pushed the change.

**Comment by kittiu** [comment]
This module is ready for review. @LoisRForgeFlow can remove the badge?

**Review by LoisRForgeFlow — APPROVED** [review]
Now it looks good to me :+1:

Functional test is correct

**Comment by LoisRForgeFlow** [comment]
@kittiu can you squash into only one commit?

**Comment by kittiu** [comment]
> @kittiu can you squash into only one commit?

Done, thanks!

**Comment by LoisRForgeFlow** [comment]
@nmoturi could you drop a review here?

**Comment by nmoturi** [comment]
Thanks @LoisRForgeFlow and @Kitti. The new description on stripe implementation works perfectly fine and looks functionally sound.

**Comment by kittiu** [comment]
> Thanks @LoisRForgeFlow and @kitti. The new description on stripe implementation works perfectly fine and looks functionally sound.

Can you click approve?

**Review by nmoturi — APPROVED** [review]

**Pull request merged**
