### PR TITLE
[13.0][ADD]base_rule_visibility_restriction

### PR DESCRIPTION
**Pull request by GuillemCForgeFlow**
@ForgeFlow

### CODE REVIEW

**Comment by GuillemCForgeFlow** [comment]
Hi @LoisRForgeFlow, this might be an interesting module to have but was forgotten 😢 . WDYT?

**Review by LoisRForgeFlow — APPROVED** [review]
It looks interesting indeed! LGTM

**Review by JordiMForgeFlow — APPROVED** [review]
LGTM 👍🏼

**Comment by LoisRForgeFlow** [comment]
@GuillemCForgeFlow can you rebase, it seems that the bot is lazy today

**Pull request merged**
