### PR TITLE
[15.0][MIG] base_tier_validation

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration
@ForgeFlow

### CODE REVIEW

**Review by etobella — APPROVED** [review]
It seems straightforward. Can you squash administrative commits?

**Review by LoisRForgeFlow — APPROVED** [review]
Tested locally, works fine! :+1:

**Comment by LoisRForgeFlow** [comment]
@etobella can you check commit history?, it is much leaner now!

**Review by etobella — APPROVED** [review]
Good for me! :+1: Thanks

**Comment by LoisRForgeFlow** [comment]
Let's go!

/ocabot merge nobump

**Pull request merged**
