### PR TITLE
[IMP][16.0] date_range: refactor calls to deprecated functions

### PR DESCRIPTION
**Pull request by bosd**
Fixing migration leftovers

### CODE REVIEW

**Review by Dranyel-Bosd — APPROVED** [review]
LGTM :+1:

**Review by lmignon — APPROVED** [review]

**Comment by lmignon** [comment]
Thank you @bosd !

**Comment by bosd** [comment]
[@lmignon](https://github.com/lmignon) Can you re-trigger the bot? The bot was having a break yesterday.

**Comment by lmignon** [comment]
Thank you for the reminder @bosd :smirk:

**Pull request merged**
