### PR TITLE
[FIX] base_tier_validation: prevent useless loop

### PR DESCRIPTION
**Pull request by fmdl**

### CODE REVIEW

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
Why is it useless? Could you elaborate the problem you are fixing?

**Comment by fmdl** [comment]
Because if you have 100 records, you overwrite 99 times the same value for the same key in user_reviews.

**Review by ByteMeAsap — APPROVED** [review]
Looks Good !!!

**Review by celm1990 — APPROVED** [review]
LGTM

**Review by bosd — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
