### PR TITLE
[14.0][IMP] base_tier_validation/server_action: Improve flow for validation conditions

### PR DESCRIPTION
**Pull request by renda-dev**
supersedes https://github.com/OCA/server-ux/pull/495

cc: @rousseldenis, @simahawk

### CODE REVIEW

**Comment by francesco-ooops** [comment]
@bosd too (approved original PR)

**Comment by bosd** [comment]
Thanks for the new PR. Can you attend to the comments of Simahawk in https://github.com/OCA/server-ux/pull/495#pullrequestreview-1329159284 ?

**Comment by renda-dev** [comment]
> Thanks for the new PR. Can you attend to the comments of Simahawk in [#495 (review)](https://github.com/OCA/server-ux/pull/495#pullrequestreview-1329159284) ?

Already done, please @simahawk let me know what you think so we can eventually discuss it here.

**Comment by bosd** [comment]
Thanks, I was also referring to this comment:

> Furthermore: can you please rewrite the commits to shorten them and remove the odoo version? Thanks

Currently commit message are still quite long. Maybe split them into multi line.
And it still conatins version number `[14.0]`

**Comment by renda-dev** [comment]
> Thanks, I was also referring to this comment:
> 
> > Furthermore: can you please rewrite the commits to shorten them and remove the odoo version? Thanks
> 
> Currently commit message are still quite long. Maybe split them into multi line. And it still conatins version number `[14.0]`

Forgot about that, thank you!

**Comment by francesco-ooops** [comment]
@bosd good for you?

**Comment by bosd** [comment]
> @bosd good for you?

Works for me, but @simahawk is the one to ask :wink:

**Comment by francesco-ooops** [comment]
good, just wanted to accumulate some positive reviews while waiting for him haha

**Review by bosd — APPROVED** [review]
Well, here's one :wink:

**Comment by francesco-ooops** [comment]
@rousseldenis @simahawk ping :)

**Comment by francesco-ooops** [comment]
@pedrobaeza could you take a look? thanks!

**Comment by pedrobaeza** [comment]
I don't have too much experience on this module, sorry.

**Review by HekkiMelody — APPROVED** [review]
Code review

**Comment by francesco-ooops** [comment]
@LoisRForgeFlow @kittiu what do you think? :)

**Review by GSLabIt — APPROVED** [review]
Code LGTM

**Comment by francesco-ooops** [comment]
@LoisRForgeFlow @kittiu gentle reminder

**Comment by kittiu** [comment]
Sorry, may I understand the situation here? https://github.com/OCA/server-ux/pull/495, why not just merge this one.
What is the difference.

**Comment by HekkiMelody** [comment]
> Sorry, may I understand the situation here? #495, why not just merge this one. What is the difference.

We simply addressed the comments that were made on the previous PR, since it had been left unattended.

**Comment by HekkiMelody** [comment]
> > Thanks, I was also referring to this comment:
> > > Furthermore: can you please rewrite the commits to shorten them and remove the odoo version? Thanks
> > 
> > 
> > Currently commit message are still quite long. Maybe split them into multi line. And it still conatins version number `[14.0]`
> 
> Forgot about that, thank you!

@renda-dev Commit messages should be less than 80 characters long. A good hint is that Github cuts them with ellipses if they're too long.

image

**Comment by francesco-ooops** [comment]
would love to have @rousseldenis and @simahawk approval :)

**Review by kittiu — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@kittiu would you mind merging? thanks!

**Comment by rvalyi** [comment]
based on the various reviews,

/ocabot merge major

**Pull request merged**
