### PR TITLE
[14.0][MIG]base_user_locale: Migration to 14.0

### PR DESCRIPTION
**Pull request by GuillemCForgeFlow**
Standard migration
@ForgeFlow

### CODE REVIEW

**Comment by ChrisOForgeFlow** [comment]
+1

**Review by dsolanki-initos — APPROVED** [review]
Functional test and code review. No major change. Looks good to me.

**Comment by dsolanki-initos** [comment]
Hello @LoisRForgeFlow,
Could you please review it?

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
