### PR TITLE
[15.0][MIG] base_tier_validation_report

### PR DESCRIPTION
**Pull request by ps-tubtim**
Standard Migration.

### CODE REVIEW

**Review by bosd — APPROVED** [review]
LGTM 👍

**Comment by Saran440** [comment]
Cheery-pick from https://github.com/OCA/server-ux/pull/602

**Review by Saran440 — APPROVED** [review]
LGTM :+1:

**Comment by bosd** [comment]
@oca-maintainers can we get a merge here?

**Comment by thomaspaulb** [comment]
> @oca-maintainers can we get a merge here?

It's `OCA/tools-maintainers`

**Pull request merged**
