### PR TITLE
[MIG] base_export_manager: Migration to 15.0

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by manuelregidor** [comment]
Hello @nicomacr Do you think you'll be able to finish this migration? Thank you!

**Comment by nicomacr** [comment]
@manuelregidor yes i've update the commit to fix pre-commit

**Comment by tarbib** [comment]
Hello @pedrobaeza 
Would it be possible to have the module merged?

**Comment by pedrobaeza** [comment]
/ocabot migration base_export_manager

See https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review and https://odoo-community.org/page/review for the rules for merging things.

**Comment by cesar-tecnativa** [comment]
Please latest commit "[[IMP] product_order_noname: black, isort, prettier](https://github.com/OCA/server-ux/pull/478/commits/6025d0ad1ec43e3f720c4ddf8993586337a6c312)" merge with previous gone

**Review by cesar-tecnativa — CHANGES_REQUESTED** [review]
Please latest commit "[[IMP] product_order_noname: black, isort, prettier](https://github.com/OCA/server-ux/pull/478/commits/6025d0ad1ec43e3f720c4ddf8993586337a6c312)" merge with previous gone

**Comment by nicomacr** [comment]
@cesar-tecnativa Done!

**Review by cesar-tecnativa — APPROVED** [review]

**Pull request merged**
