### PR TITLE
[16.0][FIX]test_base_binary_url_import: unittests

### PR DESCRIPTION
**Pull request by bosd**
fixes: ModuleNotFoundError: No module named 'responses'

### CODE REVIEW

**Comment by bosd** [comment]
@Dranyel-Bosd Please review

**Review by Dranyel-Bosd — APPROVED** [review]
LGTM :+1:

**Review by bofiltd — APPROVED** [review]
LGTM

**Comment by bosd** [comment]
@oca-maintainers Can this one be fasttracked to fix the tests?

**Review by simahawk — APPROVED** [review]

**Review by simahawk — CHANGES_REQUESTED** [review]
Sorry, approved by error :sweat: 

This is not a dep for the module, is only for testing.
Please modify only test-requirements.txt.

And... yes... it would be nice to have a key in the manifest for that :wink:

**Review by simahawk — APPROVED** [review]
ok, I'm drunk.... this is just a test module... we don't care at all :rofl:

**Comment by simahawk** [comment]
Thank you @bosd :+1:

**Pull request merged**
