### PR TITLE
[14.0][FIX] - base_search_custom_field_filter: fix filter init

### PR DESCRIPTION
**Pull request by sbejaoui**
When using the custom field filter, the user gets an error message:

```ValueError: Invalid field res.partner.ir_ui_custom_filter_3 in leaf ('ir_ui_custom_filter_3', 'ilike', 'azure')```

### CODE REVIEW

**Comment by sbejaoui** [comment]
cc/ @Cedric-Pigeon , @xavier-bouquiaux

**Comment by pedrobaeza** [comment]
Can you specify what is fixing? On previous versions, the specific attribute `custom_field_filter` was used to later intercept it on JS.

**Comment by sbejaoui** [comment]
> Can you specify what is fixing? On previous versions, the specific attribute `custom_field_filter` was used to later intercept it on JS.

I added the details to the PR description. 

Now when I see it. I believe the JS part is not needed as it works by only adding the filter via fields_view_get. And I believe `SearchBarAutoCompleteSources` does not exist any more.

**Comment by pedrobaeza** [comment]
@carlosdauden can you please check the specific case that leads you to add such JS thing?

**Comment by carlosdauden** [comment]
Commit and explanation here: https://github.com/OCA/server-ux/commit/c335dd09a4c05eb497a615e57200a62559c3ba5a

I will test

**Comment by rousseldenis** [comment]
@carlosdauden Any news on this ?

**Review by dsolanki-initos — APPROVED** [review]
Functional test and code review. Looks good to me.

**Comment by dsolanki-initos** [comment]
Hello @victoralmau Could you please review?

**Comment by dsolanki-initos** [comment]
@remytms Could you please review?

**Comment by dsolanki-initos** [comment]
@Tardo Can you please review this PR?

**Comment by rousseldenis** [comment]
@carlosdauden

**Review by rousseldenis — APPROVED** [review]

**Comment by pedrobaeza** [comment]
The problem depicted in https://github.com/OCA/server-ux/commit/c335dd09a4c05eb497a615e57200a62559c3ba5a will arise with this fix.

**Comment by dsolanki-initos** [comment]
@sbejaoui can you please check as pedro suggesion.

**Comment by dsolanki-initos** [comment]
@sbejaoui Can you please check the failed checks?

**Comment by sbejaoui** [comment]
Thank you @dsolanki-initos for the ping.

@pedrobaeza , The bug depicted in https://github.com/OCA/server-ux/commit/c335dd09a4c05eb497a615e57200a62559c3ba5a is not reproducible after this fix.

steps:
- Create a custom filter for company
- add a new partner with the same name as an existing one

I recommend to merge this PR any way because the bug it fixes is a blocking one and the module is not usable in the current state.

ezgif-2-8775a73dd8

**Comment by pedrobaeza** [comment]
The video is not reproducible.

**Comment by sbejaoui** [comment]
> The video is not reproducible.

@pedrobaeza , please check now

**Comment by dsolanki-initos** [comment]
@pedrobaeza can we merge this PR?

**Review by carlosdauden — APPROVED** [review]

**Pull request merged**
