### PR TITLE
[15.0][IMP] base_tier_validation: Avoid tier validation (error) when only browsing attachments

### PR DESCRIPTION
**Pull request by bobslee**

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Hi @bobslee 

Thanks for contributing! Could you provide a list of steps to reproduce the error that you are fixing?

Thanks!

**Comment by bobslee** [comment]
Hi @LoisRForgeFlow 

Thanks for reviewing.

Steps to reproduce the addressed issue:
1. Install a tier validation module, eg `sale_tier_validation`
2. Open a sales quotation eg. reference here SO123
3. Add 2 or more attachments to the sales quotation (SO123)
4. Request a (tier) validation for the sales quotation (SO123)
5. Browse the attachments (next, previous) in the preview.
6. Tier Validation Error is raised: "The operation is under validation."

**Comment by bobslee** [comment]
@CasVissers-360ERP FYI, under review: tier validation attachments fix.

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review

**Comment by Saran440** [comment]
@bobslee Hi, I tested with your step and it not error. or I wrong step? Can you show your step by video or image, please?
Peek 2023-01-27 10-32

**Comment by Saran440** [comment]
@bobslee I tested with your step and not found error. Did I make a mistake anywhere?
Peek 2023-01-27 10-32

**Review by bosd — APPROVED** [review]

**Comment by thomaspaulb** [comment]
Tried to replicate this problem on OCA/sale-workflow 15.0 runboat, but I'm also unable to.

@bobslee Could you post a traceback of the error perhaps? Then you know which code actually tries to write to the attachment_ids

**Pull request closed without merging**
