### PR TITLE
[15.0][MIG] base_optional_quick_create

### PR DESCRIPTION
**Pull request by kimirondon**

### CODE REVIEW

**Comment by mcassuto** [comment]
Anyone to approve this PR ?

**Review by simahawk — APPROVED** [review]
LG

**Review by leemannd — APPROVED** [review]

**Comment by akevinieron** [comment]
Ping :smile:

**Comment by desdelinux** [comment]
LGTM, ping @kimirondon

**Comment by ao-landoo** [comment]
@pedrobaeza  Can it be merged?

**Pull request merged**
