### PR TITLE
[17.0] server-ux: copier repo update

### PR DESCRIPTION
**Pull request by bosd**
This should update the maintainer tools.
Attempt to fix the xml warning.
cc: @celm1990

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Just ignore the XML warning. It's not fixed "upstream" on the copier template (in fact, it should be fixed in README generator).

**Comment by bosd** [comment]
I know, it's not a biggy.
But people, (including myself at first) where confused seeing the warning when reviewing an pr.
Thinking something is wrong in the PR.

The new release of the maintainer-tools, includes an update of the oca generator)
https://github.com/OCA/maintainer-tools/pull/596

Only it is not rolled out at all the V17 branches of the repo.
As the version of maintainer tool is pinned in pre-commit config of the repo.
https://github.com/OCA/oca-addons-repo-template/pull/239

Actually, Is this a task for the @OCA-git-bot to update all the oca repo's when there is a new release of the `oca-addons-repo-template`?

**Review by pedrobaeza — APPROVED** [review]
Sorry, I didn't know about the update in maintainer-tools.

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
Ouch!

```
base_tier_validation/models/tier_definition.py:77:89: E501 Line too long (90 > 88)
```

Please rebase and fix the long line after merging `base_tier_validation`.

**Comment by bosd** [comment]
Done! 

> base_tier_validation/models/tier_definition.py:77:89: E501 Line too long (90 > 88)

Seems like ruff does'nt auto fix these too long lines.

**Pull request merged**
