### PR TITLE
[17.0][MIG] barcode_action: Migration to 17.0

### PR DESCRIPTION
**Pull request by mpascuall**
Module migrated to version 17.0

cc https://github.com/APSL 154428

@miquelalzanillas @lbarry-apsl @javierobcn @peluko00 please review

### CODE REVIEW

**Review by peluko00 — APPROVED** [review]
Works good, tested in runboat

**Review by lbarry-apsl — APPROVED** [review]
Works, tested on the Runboat

**Comment by peluko00** [comment]
Ready for merge @pedrobaeza ?

**Comment by pedrobaeza** [comment]
/ocabot migration barcode_action

A review of a PSC/maintainer is needed, as I don't know this module.

**Comment by peluko00** [comment]
@LoisRForgeFlow can you review please, seems it's ready to merge

**Review by LoisRForgeFlow — APPROVED** [review]
Tested locally, works as expected :+1:

**Pull request merged**
