### PR TITLE
[16.0][MIG] announcement: Migration to 16.0

### PR DESCRIPTION
**Pull request by chienandalu**
cc @Tecnativa TT45864

ping @CarlosRoca13

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Only a little aesthetic thing:

imagen

**Comment by CarlosRoca13** [comment]
What you mean is about removing the label?

**Comment by CarlosRoca13** [comment]
Removed the label and added a placeholder :smile:

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
