### PR TITLE
[16.0][PORT] 630 from 14.0

### PR DESCRIPTION
**Pull request by bosd**
Port #630 from 14.0 to 16.0.

### CODE REVIEW

**Review by flotho — APPROVED** [review]
easy code review LGTM

**Review by LoisRForgeFlow — APPROVED** [review]
/ocabot merge patch

**Comment by hbrunn** [comment]
@bosd @LoisRForgeFlow this breaks tier validation for any model that doesn't have the active flag. I suggest to rework this in order to look at the model's fields and and only add the domain if the active field exists.

**Comment by LoisRForgeFlow** [comment]
@hbrunn Here you have the fwport of the fix for v16. https://github.com/OCA/server-ux/pull/647, reviews are welcomed.

**Pull request merged**
