### PR TITLE
[15.0][MIG] base_cancel_confirm : Migration to 15.0

### PR DESCRIPTION
**Pull request by moaadbourhim**

### CODE REVIEW

**Comment by moaadbourhim** [comment]
@kittiu Can you please review this PR

**Comment by kittiu** [comment]
Looks like there are still some test error. Can you check please.

**Comment by jwaes** [comment]
> Looks like there are still some test error. Can you check please.

These tests seem to fail in all PR with migrations to 15.0

**Comment by CasVissers-360ERP** [comment]
@moaadbourhim I get a traceback
```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 688, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 917, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1348, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1340, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 460, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 433, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/models.py", line 1629, in load_views
    result['fields_views'] = {
  File "/home/odoo/src/odoo/odoo/models.py", line 1630, in <dictcomp>
    v_type: self.fields_view_get(v_id, v_type if v_type != 'list' else 'tree',
  File "/home/odoo/src/user/community14/brand/models/res_brand_mixin.py", line 68, in fields_view_get
    result = super(ResBrandMixin, self).fields_view_get(
  File "/home/odoo/src/user/community/base_cancel_confirm/model/base_cancel_confirm.py", line 60, in fields_view_get
    new_arch, new_fields = View.postprocess_and_fields(doc, self._name)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 1020, in postprocess_and_fields
    name_manager = self._postprocess_view(node, model or self.model)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 1067, in _postprocess_view
    transfer_node_to_modifiers(node, node_info['modifiers'], self._context)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 88, in transfer_node_to_modifiers
    modifiers.update(ast.literal_eval(attrs))
  File "/usr/lib/python3.8/ast.py", line 99, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.8/ast.py", line 84, in _convert
    return set(map(_convert, node.elts))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 644, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: unhashable type: 'dict'
```

**Comment by CasVissers-360ERP** [comment]
@moaadbourhim Did you check my message?

**Comment by kittiu** [comment]
In addition, there are improvement in v14, you may want to consider including it here,
https://github.com/OCA/server-ux/pull/497

**Pull request closed without merging**
