### PR TITLE
[17.0][MIG] base_substate: Migration to 17.0

### PR DESCRIPTION
**Pull request by achulii**

### CODE REVIEW

**Comment by MohamedOsman7** [comment]
@achulii Code review LGTM, however there are some warnings in the tests that need to be addressed. Additionally some commits need to be squashed, so i will be also able to test the functionality through the runboat.
(check documentation: https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate)

**Review by bosd — CHANGES_REQUESTED** [review]
Thanks for your work on this!
LGTM, some minor comments:

Can you please check this warning?

```
2024-05-16 11:00:30,502 249 WARNING odoo odoo_test_helper.fake_model_loader: Wrong Import in module base_substate, the class <class 'odoo.addons.base_substate.tests.sale_test.SaleTest'> have been already imported.
Please take a look to the README on how to import test class 
2024-05-16 11:00:30,502 249 WARNING odoo odoo_test_helper.fake_model_loader: Wrong Import in module base_substate, the class <class 'odoo.addons.base_substate.tests.sale_test.SaleTest'> have been already imported.
Please take a look to the README on how to import test class 
2024-05-16 11:00:30,502 249 WARNING odoo odoo_test_helper.fake_model_loader: Wrong Import in module base_substate, the class <class 'odoo.addons.base_substate.tests.sale_test.LineTest'> have been already imported.
Please take a look to the README on how to import test class 

2024-05-16 11:00:39,253 249 WARNING odoo odoo.fields: Field base.substate.test.sale.substate_id: unknown parameter 'tracking', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 
2024-05-16 11:00:39,444 249 WARNING odoo odoo.fields: Translated stored related field (date.range.type_name) will not be computed correctly in all languages 
2024-05-16 11:00:39,445 249 WARNING odoo odoo.fields: Field base.substate.test.sale.substate_id: unknown parameter 'tracking', if this is an actual parameter you may want to override the method _valid_field_parameter on the relevant model in order to allow it 

```



As discovered in:
https://github.com/OCA/account-invoicing/pull/1595#discussion_r1669888712
This module uses wrong spelling and is inconsistent.
It occurs at multiple places. Can you please add a separate commit, to correct `Sub State` to `Substate`.

**Comment by CRogos** [comment]
Is this a followup of https://github.com/OCA/server-ux/pull/855 ?

**Comment by pedrobaeza** [comment]
Superseded by #940

**Pull request closed without merging**
