### PR TITLE
[15.0][MIG] base_revision

### PR DESCRIPTION
**Pull request by ao-landoo**
Superseeds #456 as no activity

Commits have been squashed

### CODE REVIEW

**Comment by ao-landoo** [comment]
@leemannd @JasminSForgeFlow could you review?

**Review by leemannd — APPROVED** [review]
Looks good

**Review by CRogos — APPROVED** [review]
Code and functional review LGTM!

**Comment by ao-landoo** [comment]
@pedrobaeza Can it be merged?

**Pull request merged**
