### PR TITLE
[14.0][ADD] base_module_default_filter

### PR DESCRIPTION
**Pull request by HekkiMelody**
Simple module to remove the (often useless) default filter on the apps view.

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

@pedrobaeza good for you? :)

**Comment by pedrobaeza** [comment]
Well, this can be done easily putting a favorite filter as default, so not sure about the need of this module.

**Comment by francesco-ooops** [comment]
@pedrobaeza how would you suggest to proceed in order to have such a filter automatically enabled for any db ever created?

**Comment by pedrobaeza** [comment]
Ansible or other automation tool. The effort to install the module is the same than setting the filter IMO (and both are scriptable through the same automation tool), so I would go with the one not adding code to maintain.

**Comment by francesco-ooops** [comment]
Ok, so far in our environments every new db has a set of modules installed by default so we thought of adding this one to the flow, but we'll check out how to do this with Ansible. Thanks!

**Pull request closed without merging**
