### PR TITLE
Upgrade/11.0 base technical features

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
@pedrobaeza repo is missing from https://github.com/OCA/maintainer-tools/blob/master/tools/repos_with_ids.txt. I guessed 250. Is that correct?

**Comment by pedrobaeza** [comment]
Yeah, sorry, adding them to the list

**Review by bealdav — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
@StefanRijnhart maybe a last squashing of old commits that were put split in the beginning?

**Comment by StefanRijnhart** [comment]
@pedrobaeza done!

**Pull request merged**
