### PR TITLE
[16.0] [IMP] base_tier_validation: Block notifications

### PR DESCRIPTION
**Pull request by manuelregidor**
This imp adds three additional options to configure whether tier definitions have to cause the sending of notifications when reviews get accepted, rejected or restarted (the 'on create option' is already available). This options are located in the "More Options" tab in tier definitions.

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Comment by ValentinVinagre** [comment]
@Jaimermaccione could u review ?

**Review by Jaimermaccione — APPROVED** [review]
LGTM. Functional review in local environment

**Review by HaraldPanten — APPROVED** [review]
LGTM. @etobella @ValentinVinagre Could you make a technical review, please?

THX

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by etobella — APPROVED** [review]
Technical review

**Pull request merged**
