### PR TITLE
[17.0][MIG] sequence_reset_period: Migration to 17.0

### PR DESCRIPTION
**Pull request by AEstLo**

### CODE REVIEW

**Review by thomashaunschmid86 — APPROVED** [review]

**Review by thomashaunschmid86 — APPROVED** [review]

**Review by thomashaunschmid86 — APPROVED** [review]

**Review by BT-mptas — APPROVED** [review]

**Review by BT-pmayer — APPROVED** [review]

**Comment by AEstLo** [comment]
@thomaspaulb I saw you merged last migration: https://github.com/OCA/server-ux/pull/590#issuecomment-1521021925
Could you take a look and merge this too?
Thanks

**Review by gaikaz — APPROVED** [review]
mig. changes lgtm

**Comment by thomaspaulb** [comment]
/ocabot migration sequence_reset_period

/ocabot merge nobump

@AEstLo Yes after there are enough reviews you can always ping `@OCA/tools-maintainers` to ask for a merge

**Pull request merged**
