### PR TITLE
[13.0][UPD] Repo template

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@OCA/tools-maintainers need a little bit of help here

**Comment by alexey-pelykh** [comment]
Related https://github.com/OCA/server-ux/pull/489

**Comment by alexey-pelykh** [comment]
Needs https://github.com/OCA/edi/pull/627

**Comment by alexey-pelykh** [comment]
🤔 
```
AttributeError: <module 'odoo.addons.document_quick_access_folder_auto_classification.components.document_quick_access_process' from '/__w/server-ux/server-ux/document_quick_access_folder_auto_classification/components/document_quick_access_process.py'> does not have the attribute 'decode'
```
@etobella any ideas?

**Comment by alexey-pelykh** [comment]
May this one be related https://github.com/OCA/server-ux/pull/511/commits/529ce7969c35f6180103f0b8e59325265b43aaa2 ?

**Comment by alexey-pelykh** [comment]
(https://github.com/OCA/server-ux/pull/511) @rousseldenis totally haven't noticed your PR

**Comment by rousseldenis** [comment]
> (https://github.com/OCA/server-ux/pull/511) @rousseldenis totally haven't noticed your PR

No problem. I have just one test to fix and that one should be ok

**Comment by alexey-pelykh** [comment]
@rousseldenis same error I've encountered?

**Comment by rousseldenis** [comment]
> @rousseldenis same error I've encountered?

Nope. I've already fixed it through two apt install in test.yml.

**Comment by etobella** [comment]
Error comes from https://github.com/OCA/server-ux/runs/7319392319?check_suite_focus=true#step:8:309
The main problem is that library libzbar0 is not installed.
try adding        ` "external_dependencies": {"deb": ["libzbar0"]}` on manifest

**Comment by alexey-pelykh** [comment]
@etobella thanks for the hint, added it like:

```
"external_dependencies": {
        "deb": ["libzbar0", "poppler-utils"],
        "python": ["pyzbar", "pdf2image"],
    },
```

but:

```
TestDocumentQuickAccessClassification.test_ok_pdf_multi_limit
Traceback (most recent call last):
  File "/opt/odoo/odoo/tools/misc.py", line 856, in deco
    return func(*args, **kwargs)
  File "/__w/server-ux/server-ux/document_quick_access_folder_auto_classification/tests/test_document_quick_access_auto_classification.py", line 126, in test_ok_pdf_multi_limit
    self.assertFalse(os.path.exists(os.path.join(self.tmpdir, "test_file.pdf")))
AssertionError: True is not false
```

**Comment by rousseldenis** [comment]
> @etobella thanks for the hint, added it like:
> 
> ```
> "external_dependencies": {
>         "deb": ["libzbar0", "poppler-utils"],
>         "python": ["pyzbar", "pdf2image"],
>     },
> ```
> 
> but:
> 
> ```
> TestDocumentQuickAccessClassification.test_ok_pdf_multi_limit
> Traceback (most recent call last):
>   File "/opt/odoo/odoo/tools/misc.py", line 856, in deco
>     return func(*args, **kwargs)
>   File "/__w/server-ux/server-ux/document_quick_access_folder_auto_classification/tests/test_document_quick_access_auto_classification.py", line 126, in test_ok_pdf_multi_limit
>     self.assertFalse(os.path.exists(os.path.join(self.tmpdir, "test_file.pdf")))
> AssertionError: True is not false
> ```

Same in mine. I can close it and switch to this

**Comment by rousseldenis** [comment]
@levkar even if I'd prefer to have separate commits depending what you actually fix (see my PR). Easier to future forward or backports.

**Comment by etobella** [comment]
Can you use the following commit?

https://github.com/OCA/server-ux/commit/ed3c2c3c60b907641f54a162973ed02f0b4b953a

I think it fixes your problem :smile:

**Comment by alexey-pelykh** [comment]
yay, fixed! let's merge?

**Comment by alexey-pelykh** [comment]
@simahawk if you'd spare a slice of minute to hit that merge button :)

**Review by rousseldenis — APPROVED** [review]

**Review by etobella — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Pull request merged**
