### PR TITLE
[15.0][IMP] server-ux : test performance improvement

### PR DESCRIPTION
**Pull request by josep-tecnativa**
CC @Tecnativa TT45458

### CODE REVIEW

**Comment by josep-tecnativa** [comment]
ping @pedrobaeza

**Review by chienandalu — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Comment by bosd** [comment]
I'm a bit confused by the comment:
```
        # Remove this variable in v16 and put instead:
        # from odoo.addons.base.tests.common import DISABLED_MAIL_CONTEXT
```
As the modules already have been migrated to V16 :grinning:

**Comment by pedrobaeza** [comment]
It was a mistake as these improvements were done in parallel in v15 and v16 and cherry-picking commits. You can do another PR doing such substitution.

**Pull request merged**
