### PR TITLE
12.0 mig sequence reset period

### PR DESCRIPTION
**Pull request by jaumeplanas**

### CODE REVIEW

**Review by tbaden — APPROVED** [review]
thanks for the work 👍 
I did a code review: LGTM

just some commit squashing to do
and please fix these travis warnings:
************* Module sequence_reset_period.tests.test_period
sequence_reset_period/tests/test_period.py:28: [W0622(redefined-builtin), TestSequence.test_none] Redefining built-in 'range'
sequence_reset_period/tests/test_period.py:38: [W0622(redefined-builtin), TestSequence.test_daily] Redefining built-in 'range'
sequence_reset_period/tests/test_period.py:48: [W0622(redefined-builtin), TestSequence.test_weekly] Redefining built-in 'range'
sequence_reset_period/tests/test_period.py:58: [W0622(redefined-builtin), TestSequence.test_monthly] Redefining built-in 'range'
sequence_reset_period/tests/test_period.py:68: [W0622(redefined-builtin), TestSequence.test_yearly] Redefining built-in 'range'

**Review by etobella — APPROVED** [review]
LGTM :+1: 
Can you join all your commits on a single one?

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
@jaumeplanas please avoid merge commits in PRs that screw up future commit retrieval, and also squash some of you commits across versions.

Check https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests for reference

**Comment by etobella** [comment]
@jaumeplanas Can you attend the comments in order to leave it ready to merge please?

**Comment by jaumeplanas** [comment]
@etobella @pedrobaeza  I'm trying to squash some commits across versions using instructions outlined in https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests, but I haven't succeed. I'm always finding errors showing that a fixup action is not allowed in selected commits and rebase is refused. Maybe I'm missing something. Any clues?

**Comment by etobella** [comment]
It seems that some errors where found between your commits, also, there is also merge commit, that can gives problems when rebasing.
Try the following (I will assume that OCA remote is called origin and your remote is called minorisa):
```
git checkout 12.0-mig-sequence_reset_period
git reset origin/12.0 --hard
git format-patch --keep-subject --stdout origin/12.0..minorisa/12.0-mig-sequence_reset_period -- sequence_reset_period | git am -3 --keep
```
Now you are able to rebase

**Comment by pedrobaeza** [comment]
The problem is this merge operation:

Selección_032

that screwed up the commit history. Try to avoid that operations.

Now you have to restart the branch, fetching again the commit history, and you can cherry-pick your migration commits.

**Pull request closed without merging**
