### PR TITLE
[16.0][PORT] 656 from 15.0

### PR DESCRIPTION
**Pull request by bosd**
Port #656 from 15.0 to 16.0.

### CODE REVIEW

**Review by Dranyel-Bosd — APPROVED** [review]
Functionally review :+1:

**Review by LoisRForgeFlow — APPROVED** [review]

**Comment by bosd** [comment]
Is the ocabot 🤖 taking a break?
I've noticed it on other pr's as well..
He is not doing his job as usual..

**Comment by pedrobaeza** [comment]
Yes on yesterday: https://x.com/gurneyalex/status/1725121761933422628?s=20

/ocabot merge minor

**Pull request merged**
