### PR TITLE
[15.0][FIX] base_tier_validation:Tier definition

### PR DESCRIPTION
**Pull request by Pani-k-folk**
Fix:  Modify list of specific users to show only those who belong to that particular company

### CODE REVIEW

**Comment by Pani-k-folk** [comment]
Hi @LoisRForgeFlow, Can you review this. This is the first OCA that I've attempted to modify. Hopefully, it will be beneficial to everyone.  ( = w=)

**Review by FrancoMaxime — APPROVED** [review]
LGTM: code review

**Review by newtratip — APPROVED** [review]

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
Can you fix your commit message to follow the guidelines:

[TAG] module_name: short description of change

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
The fix is also not correct, look at this example in runbot:

image

image


The check company is based in the company_id field that for users is not like in many other models, in users is just the default company, the companies that can be acceses are multiple in a user (company_ids). Thefore if you add the check_company you cannot create a tier definition in company B for a user with access in both A and B company.

**Pull request closed without merging**
