### PR TITLE
[13.0][IMP] multi_step_wizard: Go Back

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Forward-port of #165 cc @simahawk @jarroyomorales

### CODE REVIEW

**Comment by simahawk** [comment]
@alexey-pelykh pre-commit is yelling at you :wink:

**Comment by alexey-pelykh** [comment]
@simahawk fixed, it seems that multiple precommit passes are needed as I 100% did it prior to commit

**Review by simahawk — APPROVED** [review]

**Comment by kittiu** [comment]
Commit message is [12.0], not [13.0] ?
image

**Comment by alexey-pelykh** [comment]
@kittiu because it's a cherry-pick, and most migrations are full of old version numbers

**Comment by pedrobaeza** [comment]
In fact, commits must never contain Odoo version (except migrations themselves, that are named as `[MIG] <module>: Migration to X`, but it's not the version number as prefix).

See https://www.odoo.com/documentation/13.0/reference/guidelines.html#commit-message-structure

**Comment by alexey-pelykh** [comment]
@pedrobaeza absolutely, yet unless that's enforced by some check, these things will happen.

**Review by kittiu — APPROVED** [review]
LGTM

**Review by etobella — APPROVED** [review]
LGTM

**Pull request merged**
