### PR TITLE
[12.0][FIX] base_tier_validation: Unlink reviews when unlink a record

### PR DESCRIPTION
**Pull request by etobella**
The system was leaving orphan reviews.

### CODE REVIEW

**Comment by etobella** [comment]
We might need to cherry-pick this to other versions.

**Comment by etobella** [comment]
@LoisRForgeFlow I will change you user:wink: also

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Review by jarroyomorales — APPROVED** [review]

**Pull request merged**
