### PR TITLE
[14.0][ADD] sequence_range_end_buddhist_calendar

### PR DESCRIPTION
**Pull request by newtratip**
This module is change year of sequence number from A.D. to B.E.

When select option Use B.E., year in prefix / suffix will change from Anno Domini (A.D.) to Buddhist Calendar (B.E.)

Depend on sequence_range_end module https://github.com/OCA/server-ux/pull/361

cc: @kittiu

### CODE REVIEW

**Comment by kittiu** [comment]
I think this module should name `sequence_buddhist_year` and should work in every case, start or end of year, or even when not using range_year. Ie..,

* buddhist_year
* range_buddhist_year
* range_end_buddhist_year

**Comment by newtratip** [comment]
@kittiu, I agree but still can not find the best solution, however I will find the new solution and make a new PR.

Thanks for your suggest :)

**Comment by kittiu** [comment]
@newtratip any update on this?

**Comment by kittiu** [comment]
Moved to https://github.com/OCA/l10n-thailand/pull/244

@newtratip please can you close this one.

**Comment by newtratip** [comment]
@kittiu OK.

**Pull request closed without merging**
