### PR TITLE
[15.0][ADD] web_filter_header_button: New module

### PR DESCRIPTION
**Pull request by chienandalu**
This module allows to add some selected filters as buttons in the header control panel.

Peek 12-03-2024 13-50

cc @Tecnativa TT47127

@pedrobaeza do you think the name is ok?

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It should be called web_filter_button IMO

**Comment by pedrobaeza** [comment]
The commit message still indicates `filter_button`. Thinking twice, `web_filter_header_button` may be more specific.

**Comment by pedrobaeza** [comment]
I think this should be in OCA/web.

**Comment by chienandalu** [comment]
What are the nuances for a module to be in  `server-ux`?

**Comment by pedrobaeza** [comment]
Well, this is a modification of the web client, so we usually put them in oca/web.

**Comment by chienandalu** [comment]
Moved to https://github.com/OCA/web/pull/2768

**Pull request closed without merging**
