### PR TITLE
[16.0][MIG] chained_swapper: Migration to 16.0

### PR DESCRIPTION
**Pull request by kaynnan**
cc @marcelsavegnago 

#534

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is this ready to be reviewed?

**Comment by kaynnan** [comment]
> Is this ready to be reviewed?

Yes, it's ready to be reviewed

**Comment by kaynnan** [comment]
> Is this ready to be reviewed?

Not yet, I'll continue here and upload the new changes.

**Comment by kaynnan** [comment]
> Is this ready to be reviewed?

Not yet, I was reviewing the code here and I still couldn't resolve the context of when it creates with the SubElement it shows the error "Uncaught Promise > Missing field string information for the field". This occurs when I changed field_view_get to view_get because the previous method is deprecated, but when it is a many2many or many2one field, etree is not generating the element.

**Pull request closed without merging**
