### PR TITLE
[MIG] mass_operation_abstract: Migration to 15.0

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Review by jjscarafia — APPROVED** [review]
LGTM

**Comment by simahawk** [comment]
Is this module still needed? 
CC @legalsylvain

**Comment by legalsylvain** [comment]
No. @nicomacr : why do you want to migrate this module ?

**Comment by nicomacr** [comment]
@legalsylvain sorry i realized that module is not necessary now, and mass_editing module is already migrated

**Comment by legalsylvain** [comment]
Can be closed, so.

**Pull request closed without merging**
