### PR TITLE
[14.0][FIX] base_tier_validation reminder option

### PR DESCRIPTION
**Pull request by TDu**

### CODE REVIEW

**Review by sebalix — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
Hi @TDu any chance you can finish the fwport to v17 (https://github.com/OCA/server-ux/pull/931) before merging fixes in 14?

**Comment by TDu** [comment]
Hello @LoisRForgeFlow, the reminder for it hangs in my mailbox but I have so many other things to tackle at the moment...maybe soon

**Review by henrybackman — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Comment by LoisRForgeFlow** [comment]
> Hello @LoisRForgeFlow, the reminder for it hangs in my mailbox but I have so many other things to tackle at the moment...maybe soon

Hi, thanks for the info. You know, I'm just trying that versions are more or less aligned. Thanks for your efforts.

**Pull request merged**
