### PR TITLE
[FIX][17.0] date_range : error opening conditional on studio

### PR DESCRIPTION
**Pull request by micheledic**
Fixes issue https://github.com/OCA/server-ux/issues/909

### CODE REVIEW

**Comment by micheledic** [comment]
@DavidBForgeFlow @LoisRForgeFlow  ping

**Comment by micheledic** [comment]
@DavidBForgeFlow @LoisRForgeFlow @lmignon we need this fix in our production env

**Review by gbrito — APPROVED** [review]

**Comment by CLEBORGNEAPIK** [comment]
Test ok

**Comment by micheledic** [comment]
Any news? The Issue Is still on production

**Comment by micheledic** [comment]
@pedrobaeza can you check ?

**Comment by pedrobaeza** [comment]
Sorry, not using Studio, and the changes seem very wide.

**Comment by micheledic** [comment]
> Sorry, not using Studio, and the changes seem very wide.

who can check this ? the bug is still there, if somebody open studio on conditional field the error pops up
my PR only put a if above

**Comment by salvorapi** [comment]
LGTM

**Review by salvorapi — APPROVED** [review]
LGTM

**Comment by simahawk** [comment]
What about this smaller fix? https://github.com/OCA/server-ux/pull/949 
Yet I'm not sure it's complete.

**Comment by henrybackman** [comment]
I had missed the fix on the `updateLeafOperator` which is included here, thank you for this! 
I have now added it in the other PR as well:
- https://github.com/OCA/server-ux/pull/949

The fixes are similar, here the code section is wrapped in if-clause while the above PR just returns early. Impactful line changes are the same as here it is mostly indentation.

**Comment by lmignon** [comment]
@henrybackman Can you close close this one in favor of #949 ?

**Pull request closed without merging**
