### PR TITLE
[13.0][IMP] base_ir_actions_report_requence: make more generic and rename

### PR DESCRIPTION
**Pull request by JaumeBforgeFlow**

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]
Some people may argue that doing that in an already merged public module is... horrible. But As this module was merged recently, we could proceed with it if this is merged ASAP.

**Comment by pedrobaeza** [comment]
2 times `actions` word doesn't seem very correct.

**Comment by JaumeBforgeFlow** [comment]
Hi @pedrobaeza, I've updated the name

**Review by pedrobaeza — APPROVED** [review]
OK, there's still some leftover on the README, but it will be regenerated by bot. Let's merge it to avoid the propagation:

/ocabot merge patch

**Review by JoanSForgeFlow — APPROVED** [review]
LGTM! :+1:

**Pull request merged**
