### PR TITLE
[16.0][ADD] base_tier_validation_board

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
It will show all tier reviews under Dashboard

@ForgeFlow

### CODE REVIEW

**Review by ChrisOForgeFlow — APPROVED** [review]
LGTM+

**Comment by JordiBForgeFlow** [comment]
@JasminSForgeFlow I tested with purchase_tier_validation, and I can see that a user that has no permission for purchasing can list the tier reviews associated to purchase orders:

image

In mail_activity_board it used to be resolved by https://github.com/OCA/social/blob/14.0/mail_activity_board/models/mail_activity.py#L84

But I can see that this code has been removed in 15.0 onwards...

**Review by JordiMForgeFlow — APPROVED** [review]
Code review 👍🏼

**Comment by JordiBForgeFlow** [comment]
@JasminSForgeFlow in mail_activity_board this does not happen (a user that does not have permission for purchase.order cannot see activities related) due to https://github.com/odoo/odoo/blob/16.0/addons/mail/models/mail_activity.py#L375.

Can you propose the equivalent of https://github.com/odoo/odoo/blob/16.0/addons/mail/models/mail_activity.py#L375 to the base_tier_validation module?

**Comment by JasminSForgeFlow** [comment]
> @JasminSForgeFlow in mail_activity_board this does not happen (a user that does not have permission for purchase.order cannot see activities related) due to https://github.com/odoo/odoo/blob/16.0/addons/mail/models/mail_activity.py#L375.
> 
> Can you propose the equivalent of https://github.com/odoo/odoo/blob/16.0/addons/mail/models/mail_activity.py#L375 to the base_tier_validation module?

HI,
it is implemented,
Thanks

**Pull request merged**
