### PR TITLE
[IMP] server_action_mass_edit: rename mass editing line table and model

### PR DESCRIPTION
**Pull request by CLaurelB**
Add a migration script to rename the mass editing line table and model to match the new ones defined in the module.

### CODE REVIEW

**Comment by CLaurelB** [comment]
@luisg123v could you review, please?

**Review by flotho — APPROVED** [review]
easy code review
LGTM
Thanks

**Comment by pedrobaeza** [comment]
This doesn't belong here, but on 16.0: https://github.com/OCA/server-ux/blob/16.0/server_action_mass_edit/migrations/16.0.2.0.0/pre-migration.py

Please stop polluting OCA with these artifacts coming from enterprise migrations, and also don't hijack the work from others removing the copyright lines.

**Comment by flotho** [comment]
> This doesn't belong here, but on 16.0: https://github.com/OCA/server-ux/blob/16.0/server_action_mass_edit/migrations/16.0.2.0.0/pre-migration.py
> 
> Please stop polluting OCA with these artifacts coming from enterprise migrations, and also don't hijack the work from others removing the copyright lines.

hum, thanks for keeping things safe @pedrobaeza , I wouldn't have check so far before giving my approval.

**Comment by CLaurelB** [comment]
> This doesn't belong here, but on 16.0: https://github.com/OCA/server-ux/blob/16.0/server_action_mass_edit/migrations/16.0.2.0.0/pre-migration.py
> 
> Please stop polluting OCA with these artifacts coming from enterprise migrations, and also don't hijack the work from others removing the copyright lines.

Thank you for the feedback and I apologize for any inconvenience. We will consider this for future migrations, along with the comments left on this PR: https://github.com/OCA/commission/pull/535.

**Pull request closed without merging**
