### PR TITLE
[13.0][ADD] base_tier_validation_action [WIP]

### PR DESCRIPTION
**Pull request by kittiu**
Add option in definition to,

**1. Trigger server action after validate a tier**

image

**2. Auto validate tier**

image

These enhancement should complete the use case like,

* After validate the last step of PO, do "Confirm" the PO too.
* If user is on vacation and the amount is less than 1000, auto validate the PO.
* etc.

### CODE REVIEW

**Comment by kittiu** [comment]
This PR is part of the RFC  - https://github.com/OCA/server-ux/issues/192

Per say, this is actually 2 separated feature, yet quite minimal. In my opinion, I think this one can should be part of `base_tier_validation` or otherwise, it should be split into 2 `base_tier_validation_action`, `base_tier_validation_auto`

Any comment for this WIP are welcome?

**Comment by LoisRForgeFlow** [comment]
Is this still WIP?

**Comment by kittiu** [comment]
Yes, it is still WIP. Would like to hear some more comment.
I want to propose this as ENH of base_tier_validation, I think this is rather simple and can be useful.

WDYT?

**Comment by LoisRForgeFlow** [comment]
@kittiu Yes, I think this can be added in the core module. I'll be glad to review when it is ready :)

**Comment by kittiu** [comment]
Moved to https://github.com/OCA/server-ux/pull/207

**Pull request closed without merging**
