### PR TITLE
[14.0][FIX] tier_validation: Fix views from template as state was not used

### LINKED ISSUE #265: [14.0][BUG] base_tier_validation -> button template not work on all model.
Based on this,
https://github.com/OCA/server-ux/blob/14.0/base_tier_validation/templates/tier_validation_templates.xml#L8

The button will be invisible on certain status `('state','not in',['draft','sent','to approve'])`, which is ok for PR/PO.

But not OK for other model which may have different states.

@kittiu

### PR DESCRIPTION
**Pull request by etobella**
Continues #266 and fixes #265 

@LoisRForgeFlow @kittiu

### CODE REVIEW

**Comment by kittiu** [comment]
Functional Tested OK.

**Review by kittiu — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]
Code Review. LGTM

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

**Pull request merged**
