### PR TITLE
[17.0] [MIG] base_revision: migration to 17.0

### PR DESCRIPTION
**Pull request by siemenv**

### CODE REVIEW

**Review by CRogos — COMMENTED** [review]
Code LGTM

There are a lot of commits which should get squashed: 
https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate

image

**Comment by siemenv** [comment]
> Code LGTM
> 
> There are a lot of commits which should get squashed: https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate
> 
> image

Thanks for the information, it's my first OCA-migration so please let me know if my squashing was correct or not.

**Comment by CRogos** [comment]
The documentation is very long and I also had a lot of trouble to understand it. 
Basically all the OCA-git-bot, oca-ci, ... commits are triggered by some changes above. Therefore we can add these changes to the commit before.

On the left is your current commit, on the right should be the original list. The first merge was not correct, but as it belongs to the same person I would leave it merged now, but change the commit message to "[14.0][ADD] base_revision"
Also add the content of the commits according to the red arrows. In the end, the list should like look the white commits on the left site.
image

**Comment by siemenv** [comment]
Thanks for the extra explanation.
I tried to change it according to your images.

**Review by CRogos — APPROVED** [review]
Code LGTM

**Review by MohamedOsman7 — APPROVED** [review]
LGTM

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
