### PR TITLE
[16.0][mig] barcode_action: Migration to 16.0

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Comment by peluko00** [comment]
Needs review

**Comment by peluko00** [comment]
@dsolanki-initos Can you push again please?

**Comment by PR-Dev27** [comment]
@dsolanki-initos I couldn't find this working with Odoo v16. Is that missing something to working with this or not?

[scan-partner.webm](https://github.com/OCA/server-ux/assets/88542322/387f41e2-74f9-4d0d-a1b0-2d7495fb2309)

**Comment by peluko00** [comment]
I will test that later, can you push again please?

**Comment by PR-Dev27** [comment]
@dsolanki-initos As I've checked using the actual scanner device it's working as expected but it's not scanning using the console command.

**Review by yajo — APPROVED** [review]
Code review.

**Review by peluko00 — APPROVED** [review]

**Pull request merged**
