### PR TITLE
[16.0][mig] filter_multi_user: Migration to 16.0

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Review by kikopeiro — APPROVED** [review]
Seems work fine! (without code review)

**Comment by JSebastian7913** [comment]
@dsolanki-initos 
Hi, I've been reviewing functionally. The filter creation is OK, but matching by group_id to limit users is not related.

**Comment by kikopeiro** [comment]
> @dsolanki-initos Hi, I've been reviewing functionally. The filter creation is OK, but matching by group_id to limit users is not related.

Could you show an example? I remember testing this PR and the functionality was completely OK

**Comment by JSebastian7913** [comment]
I apologize, I double-checked and it works. I got confused with the group_ids field.

**Comment by dsolanki-initos** [comment]
> I apologize, I double-checked and it works. I got confused with the group_ids field.

Hi @JSebastian7913, Could you please add a review?

**Comment by kikopeiro** [comment]
Please, could someone push this migration, which from the checks carried out everything seems to indicate that it is correct?

**Comment by kikopeiro** [comment]
Hi!, @dreispt 

Please, could you push this migration, which from the checks carried out everything seems to indicate that it is correct?

**Comment by bosd** [comment]
This one should not have been merged.
It's breaking CI:
image

**Pull request merged**
