### PR TITLE
[17.0][MIG] server_action_mass_edit: Migration to 17.0

### PR DESCRIPTION
**Pull request by rov-adhoc**

### CODE REVIEW

**Comment by trisdoan** [comment]
Hi @rov-adhoc, may I ask why you closed this PR 😅?
I still see this module in the list of Migration to 17.0 plan

**Comment by Tisho99** [comment]
Hi @rov-adhoc 

May i ask you the same question? Why you closed this PR?

**Comment by rov-adhoc** [comment]
@Tisho99 @trisdoan 
Hey, I closed it because it was not functionally working. So, I'm now working on creating a new PR.
Regards!

**Comment by Tisho99** [comment]
Thank you! @rov-adhoc 

If you need reviewers in your new PR you can ping me once it's ready

You can also say its being migrated here: https://github.com/OCA/server-ux/issues/752

Regards!

**Comment by HaraldPanten** [comment]
> @Tisho99 @trisdoan Hey, I closed it because it was not functionally working. So, I'm now working on creating a new PR. Regards!

Hi, will you start working on it soon? If you can't, we can manage the migration. Let us know.

**Comment by Tisho99** [comment]
Hi @rov-adhoc 

We are going to start managing the migration in #843

Please let us know if you have made progress

Regards!

**Comment by rov-adhoc** [comment]
@Tisho99 Hey!! I made all my progress at https://github.com/OCA/server-ux/pull/838/files#diff-feb842217334a3d9ba78781c5d2ecdd3d770b7410348d017300b1c213c8232c6
But I still have the problem in get_view that does not receive the server_action_id in the context. I made some changes on the onchange method.

**Comment by Tisho99** [comment]
@rov-adhoc  Thanks for the update!

I have no idea how to resolve the problem. However, if you remain stuck with the migration I can try to help, but it will take me some time.

Greetings

**Comment by rov-adhoc** [comment]
@Tisho99 Hey! I still working on it. I will let you know if I have some updates on it.
Regards

**Pull request closed without merging**
