### PR TITLE
[16.0][MIG] base_revision

### PR DESCRIPTION
**Pull request by CRogos**
Migration using oca-port tool

### CODE REVIEW

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
Be careful, you are including changes on base_tier_validation here too.

**Comment by CRogos** [comment]
@LoisRForgeFlow  you are totally right... I did not recognise it. The problem is that the pre-commit task on 16.0 branch is not finishing without errors.

I did a separate PR for the pre-commit issues: https://github.com/OCA/server-ux/pull/600

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM

**Review by MohamedOsman7 — APPROVED** [review]

**Pull request merged**
