### PR TITLE
[14.0][MIG] base_optional_quick_create

### PR DESCRIPTION
**Pull request by kimirondon**

### CODE REVIEW

**Comment by fshah-initos** [comment]
@kimirondon It seems you haven't followed up guidelines of OCA. Please refer this link https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

**Comment by SimoRubi** [comment]
@kimirondon I already migrated this module in https://github.com/OCA/server-ux/pull/312, can you have a look?

**Comment by kimirondon** [comment]
> @kimirondon It seems you haven't followed up guidelines of OCA. Please refer this link https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

**Comment by kimirondon** [comment]
@fshah-initos  hello! i recovered the commit history, let me know if it's fine.

**Comment by kimirondon** [comment]
@SimoRubi hello!! thanks for the info, i was missing the entire commit history, i checked your PR it seems to fail because of the unit test, i had the same problem and i fixed adding 2 more test with a "test" model.

**Comment by fshah-initos** [comment]
Hi @kimirondon ,
As @SimoRubi already opned the PR before you and got one approval.

**Comment by fshah-initos** [comment]
Hi @kimirondon 
You need to add seperate commit for Pre-commit as per guideline.

**Comment by SimoRubi** [comment]
> @SimoRubi hello!! thanks for the info, i was missing the entire commit history, i checked your PR it seems to fail because of the unit test, i had the same problem and i fixed adding 2 more test with a "test" model.

Hi, I cherry-picked your migration commit in https://github.com/OCA/server-ux/pull/312 so we have increased coverage over there too, can you have a look?
Maybe we can focus on merging that one since it already has a positive review

**Comment by simahawk** [comment]
already done and merged on #312

**Pull request closed without merging**
