### PR TITLE
[13.0][IMP] base_tier_validation: make module multi-company compatible.

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Closed https://github.com/OCA/server-ux/issues/140.

@ForgeFlow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@CasVissers-360ERP Sorry for the long wait, but I absolutely forgot this issue and now I just hit into it :sweat_smile:. As you can see your pseudo-code in the issue was quite correct! Your review is welcomed.

**Review by HviorForgeFlow — APPROVED** [review]
:+1:

**Review by etobella — APPROVED** [review]

**Comment by CasVissers-360ERP** [comment]
Thnx for fixing!

**Pull request merged**
