### PR TITLE
[17.0][MIG] base_optional_quick_create: Migration to 17.0

### PR DESCRIPTION
**Pull request by jaydeep32**
In Odoo17, Odoo has removed these 2 methods, `_patch_method` and `_revert_method.` According to their description here in PR [110370](https://github.com/odoo/odoo/pull/110370). They think this is only used in test cases and needs a proper use case.

So in a new update, they have removed these methods and inside test cases, they now use `patch` from `unittest.mock`.
In this module, I guess we can not use that since it will confuse people since this `patch` method is coming from a unit test.

So, as a solution, I added again these 2 methods in the module itself.

### CODE REVIEW

**Comment by desdelinux** [comment]
Hi @jaydeep32 runbot not working

**Comment by jaydeep32** [comment]
@desdelinux could be pelase guide me how can I make runbot running. Because I am unable to understand why it is not running.

**Comment by desdelinux** [comment]
> @desdelinux could be pelase guide me how can I make runbot running. Because I am unable to understand why it is not running.

@jaydeep32 Force your last push to try to regenerate the runbot again

**Comment by suniagajose** [comment]
Hi @lmignon 

Can we merge this?

**Comment by suniagajose** [comment]
@lmignon 

> /ocabot migration base_optional_quick_create

apparently, it didn't work

cc @desdelinux

**Comment by suniagajose** [comment]
@lmignon 

can you ty again, please?

thanks

**Review by antoniocanovas — APPROVED** [review]
Functional review OK !!

**Review by nguyenminhchien — CHANGES_REQUESTED** [review]
Functional test ok, but better if you change the commit title from "[MIG] : Migration to 17.0" to "[MIG] base_optional_quick_create: Migration to 17.0", and squash these 2 commits into the previous one
image

**Review by nguyenminhchien — APPROVED** [review]

**Review by yankinmax — APPROVED** [review]

**Comment by desdelinux** [comment]
This is ready @lmignon Please merged

**Comment by gurneyalex** [comment]
@jaydeep32 can you remove the `readme/*.rst` files? This should allow merging.

**Comment by suniagajose** [comment]
hi @jaydeep32 

you have a message here, it's a small fix to set as ready to merge...

can you do it? please...

regards

**Comment by jaydeep32** [comment]
Hello @gurneyalex I have removed these files.
Sorry for the delay. I did not realize there was a message for me here.

**Pull request merged**
